package com.github.itskenny0.r1ha.core.lovelace

import androidx.compose.runtime.Immutable
import kotlinx.serialization.json.JsonObject

/**
 * Typed in-memory model for a parsed HA Lovelace dashboard configuration.
 *
 * Mirrors the subset of `lovelace/config` shape that the dashboards renderer
 * understands today. Any card type we don't model is preserved as
 * [LovelaceCard.Unsupported] with its raw JSON payload intact, so the screen
 * can still show a placeholder + the original config for debugging without
 * dropping it from the view.
 *
 * Read-only on R1HA's side: parsing happens once per dashboard fetch and the
 * tree is treated as immutable. Local-only edits land as a separate overrides
 * layer (see [LovelaceOverrides]) keyed by `(viewPath, cardIndex)`, applied at
 * render time so the imported HA config is never mutated.
 *
 * @Immutable so Compose can skip recomposition when references haven't changed.
 */
@Immutable
data class LovelaceConfig(
    val title: String?,
    val views: List<LovelaceView>,
    /**
     * `true` when the dashboard is entirely generated by an HA *strategy*
     * (the `strategy:` key at the config root, with no concrete `views`).
     * HA's default auto-dashboard is the canonical example: the server only
     * returns `{ "strategy": { "type": "original-states" } }` and expects the
     * frontend to expand it client-side, which R1HA can't do natively. The
     * screen reads this flag to show an "open in Lovelace" affordance instead
     * of silently rendering an empty dashboard.
     */
    val isStrategyGenerated: Boolean = false,
)

/** One view inside a dashboard. corresponds to a tab in HA's frontend. */
@Immutable
data class LovelaceView(
    /** User-facing title; falls back to the path or index when empty. */
    val title: String?,
    /**
     * URL-style identifier HA uses to address the view (e.g. "lights",
     * "default_view"). Stable across HA restarts; we key local overrides
     * against it so reordering views in HA doesn't shuffle our overrides.
     * Falls back to the index-as-string when the YAML omits it.
     */
    val path: String,
    /** Optional MDI icon string (`mdi:lightbulb` etc.). */
    val icon: String?,
    /**
     * `true` when the view should render its cards in panel mode (single
     * card filling the viewport). We honour this when rendering: a `panel: true`
     * view with one card hides the surrounding scroll/padding chrome.
     */
    val panel: Boolean,
    /**
     * The parsed cards in display order. Empty when the view exists but
     * has no cards (legitimate during early-edit on HA's side).
     */
    val cards: List<LovelaceCard>,
    /**
     * The view's top-level `badges:` array (HA renders these as a row of
     * chips above the cards). Empty when the view declares none. Each badge
     * is an entity-state chip with an optional tap action; see [LovelaceBadge].
     */
    val badges: List<LovelaceBadge> = emptyList(),
    /**
     * `true` when this view delegates its layout to an HA *strategy* (a
     * `strategy:` key on the view, or on every one of its sections) and so
     * carries no concrete cards we can render. The screen surfaces the
     * "open in Lovelace" affordance for such a view rather than an empty
     * scroll. A view that mixes a strategy section with concrete sections
     * keeps the concrete cards and is NOT flagged.
     */
    val isStrategyGenerated: Boolean = false,
)

/**
 * Sealed hierarchy of card types R1HA renders natively. Adding a new
 * type means: declare a data class here, parse it in [LovelaceParser],
 * and add a branch in [com.github.itskenny0.r1ha.feature.dashboards.cards.LovelaceCardRenderer].
 *
 * Every variant carries [raw] so the editor's JSON view can show + edit
 * the original config without round-tripping through our typed model
 * (which would silently drop fields we don't understand yet).
 */
@Immutable
sealed class LovelaceCard {
    /** Card type string from the original config (`"entities"`, `"tile"`, etc.). */
    abstract val type: String

    /** Raw JSON config as HA returned it; the editor + Unsupported renderer
     *  both rely on this being preserved verbatim. */
    abstract val raw: JsonObject

    /** Vertical list of entity rows. */
    @Immutable
    data class Entities(
        override val raw: JsonObject,
        val title: String?,
        val showHeaderToggle: Boolean?,
        val entities: List<EntityRow>,
    ) : LovelaceCard() {
        override val type: String = "entities"
    }

    /** Compact grid of entity glyphs + state readouts. */
    @Immutable
    data class Glance(
        override val raw: JsonObject,
        val title: String?,
        val entities: List<EntityRow>,
        val columns: Int?,
        val showName: Boolean,
        val showState: Boolean,
        val showIcon: Boolean,
    ) : LovelaceCard() {
        override val type: String = "glance"
    }

    /** Single tappable action button. Either a bare action (no entity) or
     *  wired to a specific entity for state-coloured display. */
    @Immutable
    data class Button(
        override val raw: JsonObject,
        val entityId: String?,
        val name: String?,
        val icon: String?,
        val showName: Boolean,
        val showIcon: Boolean,
        val showState: Boolean,
        val tapAction: LovelaceAction?,
    ) : LovelaceCard() {
        override val type: String = "button"
    }

    /**
     * Shortcut card (HA 2026.5): a tile-shaped one-tap launcher. Carries no
     * entity; the whole card fires [tapAction] (navigate / url / call-service /
     * assist). [name] / [icon] / [color] are optional overrides; when null HA
     * resolves them from the action (we best-effort the name from a navigate
     * path at render time and otherwise show a generic label).
     */
    @Immutable
    data class Shortcut(
        override val raw: JsonObject,
        val name: String?,
        val icon: String?,
        val color: String?,
        val tapAction: LovelaceAction?,
    ) : LovelaceCard() {
        override val type: String = "shortcut"
    }

    /** Modern compact tile (HA's current first-class card type). */
    @Immutable
    data class Tile(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val icon: String?,
        val hideState: Boolean,
        val vertical: Boolean,
        val color: String?,
        val tapAction: LovelaceAction?,
        // HA's `features:` array. Each entry renders as a control row below the
        // tile body (cover open/close, light brightness, fan speed, climate HVAC
        // modes, alarm modes, lock commands, toggle, target temperature, select
        // options). A feature type R1HA doesn't model parses to
        // LovelaceTileFeature.Unsupported and is skipped at render time.
        val features: List<LovelaceTileFeature> = emptyList(),
    ) : LovelaceCard() {
        override val type: String = "tile"
    }

    /** Dedicated light card. Brightness + on/off; for full colour control
     *  the card-stack archetype is still the right surface. */
    @Immutable
    data class Light(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val icon: String?,
    ) : LovelaceCard() {
        override val type: String = "light"
    }

    /** Gauge readout for one numeric entity. */
    @Immutable
    data class Gauge(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val unit: String?,
        val min: Double,
        val max: Double,
        val needle: Boolean,
        val severity: GaugeSeverity?,
        // HA's modern `segments:` band format (takes precedence over severity
        // when both are set, matching hui-gauge-card). Each segment colours the
        // arc from its `from` to the next segment's `from`. Empty when the gauge
        // uses severity or a single fill.
        val segments: List<GaugeSegment> = emptyList(),
    ) : LovelaceCard() {
        override val type: String = "gauge"
    }

    /** Weather card with current conditions + optional forecast strip. */
    @Immutable
    data class WeatherForecast(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val showCurrent: Boolean,
        val showForecast: Boolean,
        val forecastType: String?,
        val forecastSlots: Int?,
    ) : LovelaceCard() {
        override val type: String = "weather-forecast"
    }

    /** Markdown body, optionally Jinja-templated at render time. */
    @Immutable
    data class Markdown(
        override val raw: JsonObject,
        val title: String?,
        val content: String,
    ) : LovelaceCard() {
        override val type: String = "markdown"
    }

    /** Static section heading inside a view. */
    @Immutable
    data class Heading(
        override val raw: JsonObject,
        val heading: String,
        val headingStyle: String,
        val icon: String?,
    ) : LovelaceCard() {
        override val type: String = "heading"
    }

    /** Vertical stack of child cards. */
    @Immutable
    data class VerticalStack(
        override val raw: JsonObject,
        val title: String?,
        val cards: List<LovelaceCard>,
    ) : LovelaceCard() {
        override val type: String = "vertical-stack"
    }

    /** Horizontal stack of child cards. */
    @Immutable
    data class HorizontalStack(
        override val raw: JsonObject,
        val title: String?,
        val cards: List<LovelaceCard>,
    ) : LovelaceCard() {
        override val type: String = "horizontal-stack"
    }

    /** Grid of child cards in `columns` columns. */
    @Immutable
    data class Grid(
        override val raw: JsonObject,
        val title: String?,
        val columns: Int,
        val square: Boolean,
        val cards: List<LovelaceCard>,
    ) : LovelaceCard() {
        override val type: String = "grid"
    }

    /** Shows its [card] only when every condition in [conditions] passes. */
    @Immutable
    data class Conditional(
        override val raw: JsonObject,
        val conditions: List<LovelaceCondition>,
        val card: LovelaceCard,
    ) : LovelaceCard() {
        override val type: String = "conditional"
    }

    /**
     * Single-entity sensor card. Shows the friendly name + current value
     * and, when `graph: line`, a small history line chart of the sensor's
     * recent values (fetched lazily by the renderer).
     */
    @Immutable
    data class Sensor(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val icon: String?,
        val unit: String?,
        /** `true` when HA's `graph: line` is set; renders the history chart. */
        val graph: Boolean,
        /** Hours of history the line graph spans (HA's `hours_to_show`). */
        val hoursToShow: Int,
        val detail: Int?,
    ) : LovelaceCard() {
        override val type: String = "sensor"
    }

    /**
     * Picture card with overlaid entity chips. Background is a static
     * [image] URL or, when [cameraImage] / an `entity` with an
     * `entity_picture` is set, that entity's picture. [entities] render as
     * small state chips along the bottom edge.
     */
    @Immutable
    data class PictureGlance(
        override val raw: JsonObject,
        val title: String?,
        /** Static background image URL (`image:`). Null when driven by an entity picture. */
        val image: String?,
        /** Entity whose `entity_picture` attribute supplies the background. */
        val cameraImage: String?,
        val entities: List<EntityRow>,
        val tapAction: LovelaceAction?,
    ) : LovelaceCard() {
        override val type: String = "picture-glance"
    }

    /**
     * Picture card bound to a single entity. Background image (static or the
     * entity's `entity_picture`) with the entity's name + state overlaid;
     * tapping fires the entity's action.
     */
    @Immutable
    data class PictureEntity(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val image: String?,
        val showName: Boolean,
        val showState: Boolean,
        val tapAction: LovelaceAction?,
    ) : LovelaceCard() {
        override val type: String = "picture-entity"
    }

    /**
     * Area card: an area name + a representative strip of the area's
     * controls / sensors. R1HA can't resolve an area's member entities
     * locally (that needs the area registry), so the card renders the
     * configured [name]/[area] heading plus any explicitly-listed
     * [entities]; an area with no listed entities shows just the heading.
     */
    @Immutable
    data class Area(
        override val raw: JsonObject,
        /** HA `area` id. */
        val area: String,
        val name: String?,
        val image: String?,
        /** Entities the config explicitly attached to the area card, if any. */
        val entities: List<EntityRow>,
        val navigationPath: String?,
    ) : LovelaceCard() {
        override val type: String = "area"
    }

    /**
     * History-graph card: a multi-entity history line chart. The renderer
     * fetches each entity's history and overlays the numeric series on a
     * shared canvas; non-numeric entities are skipped from the line plot.
     */
    @Immutable
    data class HistoryGraph(
        override val raw: JsonObject,
        val title: String?,
        val entities: List<EntityRow>,
        val hoursToShow: Int,
    ) : LovelaceCard() {
        override val type: String = "history-graph"
    }

    /** Alarm-panel keypad card. Mirrors the cardstack AlarmPanel. */
    @Immutable
    data class AlarmPanel(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        /** Subset of HA's `states` config (arm modes to surface). Empty = all. */
        val states: List<String>,
    ) : LovelaceCard() {
        override val type: String = "alarm-panel"
    }

    /**
     * Map card: entities with `latitude`/`longitude` attributes plotted on
     * an abstract canvas (mirrors the Zones map). No real map tiles.
     */
    @Immutable
    data class Map(
        override val raw: JsonObject,
        val title: String?,
        val entities: List<EntityRow>,
        val hoursToShow: Int?,
    ) : LovelaceCard() {
        override val type: String = "map"
    }

    /**
     * Thermostat card bound to one `climate.*` entity. Surfaces the current
     * temperature reading, a target-setpoint stepper, and the HVAC-mode chip
     * row (gated on the entity's advertised `hvac_modes`). Mirrors the
     * card-stack climate control idiom; service calls ride the standard
     * [LovelaceAction.CallService] path.
     */
    @Immutable
    data class Thermostat(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
    ) : LovelaceCard() {
        override val type: String = "thermostat"
    }

    /**
     * Media-control card bound to one `media_player.*` entity. Shows the
     * now-playing line, a transport row (previous / play-pause / next), and a
     * volume stepper, each gated on the player's advertised
     * `supported_features`. Service calls ride the standard
     * [LovelaceAction.CallService] path.
     */
    @Immutable
    data class MediaControl(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
    ) : LovelaceCard() {
        override val type: String = "media-control"
    }

    /**
     * Humidifier card bound to one `humidifier.*` entity. Surfaces an on/off
     * toggle, the target-humidity stepper, and the available-mode chip row
     * (when the entity advertises `available_modes`). Service calls ride the
     * standard [LovelaceAction.CallService] path.
     */
    @Immutable
    data class Humidifier(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
    ) : LovelaceCard() {
        override val type: String = "humidifier"
    }

    /**
     * Entity-filter card: a list of candidate [entities] narrowed at render
     * time to only those whose live state matches one of [stateFilter]. HA's
     * card supports rich per-condition filters; we model the common
     * "string state equals" form (the `state_filter: ["on", "home"]`
     * shorthand) since that covers the bulk of real configs. The surviving
     * entities render as an entities-style list. An empty [stateFilter]
     * leaves every entity visible (HA's behaviour when no filter is given).
     */
    @Immutable
    data class EntityFilter(
        override val raw: JsonObject,
        val title: String?,
        val entities: List<EntityRow>,
        /** State strings an entity must currently match to be shown. */
        val stateFilter: List<String>,
        /** HA's `show_empty`: when false the whole card hides if nothing
         *  passes the filter. Defaults true (HA's default). */
        val showEmpty: Boolean,
    ) : LovelaceCard() {
        override val type: String = "entity-filter"
    }

    /**
     * Statistic card: a single long-term-statistics readout for one entity.
     * Shows the requested [statType] aggregate (mean / min / max / sum /
     * change / state) computed over [period] worth of recorder buckets. The
     * renderer fetches `statistics_during_period` lazily; an entity HA's
     * recorder doesn't track shows a graceful "no statistics" placeholder.
     */
    @Immutable
    data class Statistic(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        /** HA's `stat_type`: one of mean/min/max/sum/state/change. */
        val statType: String,
        /** Human-friendly period label HA's card accepts (`day`, `week`,
         *  `month`, `year`). Drives the lookback window. */
        val period: String,
    ) : LovelaceCard() {
        override val type: String = "statistic"
    }

    /**
     * Logbook card: a recent-events feed scoped to a set of [entities].
     * The renderer fetches HA's logbook and shows the entries whose entity
     * falls in the configured set (or every entry when none are listed),
     * going back [hoursToShow] hours.
     */
    @Immutable
    data class Logbook(
        override val raw: JsonObject,
        val title: String?,
        /** Entity ids to scope the feed to. Empty = show the whole logbook. */
        val entities: List<String>,
        val hoursToShow: Int,
    ) : LovelaceCard() {
        override val type: String = "logbook"
    }

    /**
     * Clock card: a self-contained local-time display. Carries no entities;
     * the renderer ticks a local clock. [showSeconds] mirrors HA's option;
     * [analog] selects the analog face over the default digital readout.
     */
    @Immutable
    data class Clock(
        override val raw: JsonObject,
        val title: String?,
        val showSeconds: Boolean,
        val analog: Boolean,
    ) : LovelaceCard() {
        override val type: String = "clock"
    }

    /**
     * Distribution card (HA 2026.2): one proportional segmented bar showing how
     * a numeric value splits across [entries], with a legend below. Each entry
     * contributes a segment sized by its current numeric state; non-numeric or
     * negative states contribute zero.
     */
    @Immutable
    data class Distribution(
        override val raw: JsonObject,
        val title: String?,
        val entries: List<DistributionEntry>,
    ) : LovelaceCard() {
        override val type: String = "distribution"
    }

    /** Any card type we don't natively render.
     *
     * Best-effort fallback: even for a type we don't model, most cards carry
     * enough JSON to render *something* more useful than a raw dump. The
     * parser captures:
     *  - [entityRefs]: entity ids pulled from an `entity` (string) or
     *    `entities` (array) key. Covers the bulk of `custom:*` cards
     *    (mushroom-*, button-card, etc.); the renderer shows a generic tile
     *    per ref with live state + tap-to-toggle.
     *  - [url]: the `url` of an `iframe` card, which the renderer embeds in a
     *    sandboxed WebView.
     *  - [friendlyType]: a human-readable label for the caption (the raw
     *    `custom:` prefix stripped), falling back to [type].
     *
     * When none of these are present the renderer keeps the original
     * placeholder + expandable raw-JSON affordance. */
    @Immutable
    data class Unsupported(
        override val raw: JsonObject,
        override val type: String,
        val entityRefs: List<String> = emptyList(),
        val url: String? = null,
        val friendlyType: String = type,
    ) : LovelaceCard()
}

/**
 * One row inside an entities-card-like list (entities / glance).
 *
 * HA accepts either a bare entity_id string or a richer object with name +
 * icon + secondary_info overrides; both shapes resolve to this same row.
 */
@Immutable
data class EntityRow(
    val entityId: String,
    /** Override label; null falls back to the entity's `friendly_name`. */
    val name: String?,
    /** Override icon string ("mdi:lightbulb"). Null = derived from domain. */
    val icon: String?,
    /**
     * What to render in the small secondary line under the primary state.
     * HA accepts a fixed enum: "last-changed", "last-triggered",
     * "last-updated", "area", "position", "state", "tilt-position",
     * "brightness", "entity-id". Free-form for now; renderers handle the
     * subset that maps cleanly to data we already have.
     */
    val secondaryInfo: String?,
)

/** One entry of a [LovelaceCard.Distribution]'s `entities:` list. */
@Immutable
data class DistributionEntry(
    val entityId: String,
    val name: String?,
    /** HA `color`: a theme colour name or `#rrggbb`. Null = state-derived. */
    val color: String?,
)

/**
 * One badge chip from a view's top-level `badges:` array. HA renders these as
 * a horizontal row of pills above the cards, each showing a leading icon, the
 * entity's live state value, and (optionally) a name, with a configurable tap
 * action.
 *
 * HA accepts either a bare entity-id string (`sensor.time`) or a richer object
 * (`{type: entity, entity: ..., show_state: true, ...}`); both resolve to this
 * same model. Defaults mirror HA's entity-badge: state shown, name hidden, icon
 * shown. A badge with no resolvable entity (a `type: custom:*` badge we can't
 * model) parses to one with a null [entityId] and renders a minimal text chip
 * from its [name] rather than being dropped.
 */
@Immutable
data class LovelaceBadge(
    /** Target entity id (`domain.object_id`). Null for an entity-less badge. */
    val entityId: String?,
    /** Override label; null falls back to the entity's `friendly_name`. */
    val name: String?,
    /** Override icon string ("mdi:clock-time-eight-outline"). Null = derived
     *  from the entity's domain / device_class. */
    val icon: String?,
    /** HA `color`: a theme colour name or `#rrggbb`. Null = state-derived accent. */
    val color: String?,
    val showName: Boolean,
    val showState: Boolean,
    val showIcon: Boolean,
    /** Tap target. Null = the entity's domain-default action (more-info etc.),
     *  resolved at dispatch time. */
    val tapAction: LovelaceAction?,
)

/**
 * Subset of HA's action_config we understand. Tap on a button card or
 * tile card fires one of these; unknown variants degrade to a no-op.
 */
@Immutable
sealed class LovelaceAction {
    @Immutable
    data class CallService(
        val service: String,
        val entityId: String?,
        val data: JsonObject?,
    ) : LovelaceAction()

    @Immutable
    data class Navigate(val path: String) : LovelaceAction()

    @Immutable
    data class Url(val url: String) : LovelaceAction()

    /**
     * `toggle` / `more-info` / `none`. [entityId] carries the target so the
     * dispatcher can resolve the entity (and its live state, for a toggle)
     * without relying on a card-level fallback. Null only when the action
     * came from config with no resolvable entity (the dispatcher then falls
     * back to the card's own entity id).
     */
    @Immutable
    data class Builtin(val name: String, val entityId: String? = null) : LovelaceAction()
}

/** Severity bands for the gauge card. colour the needle when the value
 *  passes a threshold. */
@Immutable
data class GaugeSeverity(
    val green: Double?,
    val yellow: Double?,
    val red: Double?,
)

// One segment of a gauge's `segments:` array (HA's modern band format). A
// segment colours the arc from `from` up to the next segment's `from` (or max
// for the last) with `color` (an HA theme-colour name or a literal #rrggbb).
@Immutable
data class GaugeSegment(
    val from: Double,
    val color: String,
)

// One entry of a `tile` card's `features:` array. HA renders each below the
// tile body as a control row (cards/tile-features). R1HA models the high-value
// subset; anything else parses to Unsupported and is skipped. The feature is
// scoped to the tile's entity, so the renderer gates each control on that
// entity's domain and advertised features.
@Immutable
sealed class LovelaceTileFeature {
    abstract val type: String

    @Immutable
    data object CoverOpenClose : LovelaceTileFeature() {
        override val type: String = "cover-open-close"
    }

    @Immutable
    data object CoverPosition : LovelaceTileFeature() {
        override val type: String = "cover-position"
    }

    @Immutable
    data object LightBrightness : LovelaceTileFeature() {
        override val type: String = "light-brightness"
    }

    @Immutable
    data object FanSpeed : LovelaceTileFeature() {
        override val type: String = "fan-speed"
    }

    @Immutable
    data class ClimateHvacModes(val modes: List<String>) : LovelaceTileFeature() {
        override val type: String = "climate-hvac-modes"
    }

    @Immutable
    data class AlarmModes(val modes: List<String>) : LovelaceTileFeature() {
        override val type: String = "alarm-modes"
    }

    @Immutable
    data object LockCommands : LovelaceTileFeature() {
        override val type: String = "lock-commands"
    }

    @Immutable
    data object Toggle : LovelaceTileFeature() {
        override val type: String = "toggle"
    }

    @Immutable
    data object TargetTemperature : LovelaceTileFeature() {
        override val type: String = "target-temperature"
    }

    @Immutable
    data class SelectOptions(val options: List<String>) : LovelaceTileFeature() {
        override val type: String = "select-options"
    }

    /** Media-player playback controls row. [controls] is HA's ordered list from
     *  {turn_on, turn_off, media_play, media_pause, media_play_pause,
     *  media_stop, media_previous_track, media_next_track, volume_down,
     *  volume_up, volume_mute, shuffle, repeat}. Empty = HA's default trio. */
    @Immutable
    data class MediaPlayback(val controls: List<String>) : LovelaceTileFeature() {
        override val type: String = "media-player-playback"
    }

    /** Media-player source selector. [sources] optionally filters/reorders. */
    @Immutable
    data class MediaSource(val sources: List<String>) : LovelaceTileFeature() {
        override val type: String = "media-player-source"
    }

    /** Media-player sound-mode selector. [soundModes] optionally filters/reorders. */
    @Immutable
    data class MediaSoundMode(val soundModes: List<String>) : LovelaceTileFeature() {
        override val type: String = "media-player-sound-mode"
    }

    /** Media-player volume +/- buttons. [step] is the percent nudge (default 5);
     *  [showMute] adds a mute toggle. */
    @Immutable
    data class MediaVolumeButtons(val step: Int, val showMute: Boolean) : LovelaceTileFeature() {
        override val type: String = "media-player-volume-buttons"
    }

    /** Media-player volume slider (stepper in-card). [showMute] adds a mute toggle. */
    @Immutable
    data class MediaVolumeSlider(val showMute: Boolean) : LovelaceTileFeature() {
        override val type: String = "media-player-volume-slider"
    }

    /** Weather temperature-forecast bar strip. [forecastType] is daily /
     *  twice_daily / hourly; [showLabels] toggles the axis labels; [color] is
     *  an optional theme colour / hex override. */
    @Immutable
    data class TemperatureForecast(
        val forecastType: String,
        val color: String?,
        val showLabels: Boolean,
    ) : LovelaceTileFeature() {
        override val type: String = "temperature-forecast"
    }

    /** Weather precipitation-forecast bar strip. [precipitationType] is amount /
     *  probability. */
    @Immutable
    data class PrecipitationForecast(
        val forecastType: String,
        val precipitationType: String,
        val color: String?,
        val showLabels: Boolean,
    ) : LovelaceTileFeature() {
        override val type: String = "precipitation-forecast"
    }

    @Immutable
    data class Unsupported(override val type: String) : LovelaceTileFeature()
}

/**
 * Condition for [LovelaceCard.Conditional] and per-card `visibility:`. Mirrors
 * HA's `checkConditionsMet` (src/panels/lovelace/common/validate-condition.ts):
 * `state` / `state_not`, `numeric_state` (with attribute + cross-entity bound
 * support), the legacy entity+state shorthand, and the `and` / `or` / `not`
 * logical groups (nested arbitrarily deep). A condition shape we cannot
 * evaluate locally maps to [Never] so the wrapped card is hidden rather than
 * shown: a condition exists precisely to gate visibility, and showing a card
 * whose gate we cannot evaluate is the wrong default (it leaks cards HA would
 * hide). The two deliberate fail-open shapes are [AlwaysTrue] (used for
 * `screen` media-queries we can't evaluate) and [User] (the logged-in-user id
 * isn't reachable in the renderer today; see the evaluator).
 */
@Immutable
sealed class LovelaceCondition {
    /**
     * HA `state` / `state_not` condition. [states] is the set of accepted
     * state strings (HA allows a single `state:` value or a `state:` list).
     * When [negate] is true (a `state_not` condition) the rule passes when the
     * entity's state is NOT in [states]. [attribute] (HA's `attribute:` key)
     * compares the named attribute rather than the entity's state when set.
     */
    @Immutable
    data class StateEquals(
        val entityId: String,
        val states: List<String>,
        val negate: Boolean = false,
        val attribute: String? = null,
    ) : LovelaceCondition() {
        /** Back-compat single-state constructor used by tests + simple call sites. */
        constructor(entityId: String, state: String, negate: Boolean = false) :
            this(entityId, listOf(state), negate, null)
    }

    /**
     * HA `numeric_state`. A bound is either a literal number ([above] /
     * [below]) or a reference to another entity's numeric state ([aboveEntity]
     * / [belowEntity], HA's "above: sensor.x" form). [attribute] compares the
     * named attribute instead of the entity's state. When a bound is an entity
     * reference the literal counterpart is null and vice-versa; the evaluator
     * resolves the referenced entity at evaluation time.
     */
    @Immutable
    data class NumericState(
        val entityId: String,
        val above: Double?,
        val below: Double?,
        val aboveEntity: String? = null,
        val belowEntity: String? = null,
        val attribute: String? = null,
    ) : LovelaceCondition()

    /** HA `and`: passes only when EVERY nested condition passes. An empty
     *  group is vacuously true (matches HA's `checkAndCondition`). */
    @Immutable
    data class And(val conditions: List<LovelaceCondition>) : LovelaceCondition()

    /** HA `or`: passes when ANY nested condition passes. An empty group is
     *  vacuously true (matches HA's `checkOrCondition`, which returns true
     *  when `conditions` is absent). */
    @Immutable
    data class Or(val conditions: List<LovelaceCondition>) : LovelaceCondition()

    /** HA `not`: the negation of an AND over the group, i.e. it passes when NOT
     *  every nested condition passes (at least one fails). An empty group is
     *  true (matches HA's `checkNotCondition`). */
    @Immutable
    data class Not(val conditions: List<LovelaceCondition>) : LovelaceCondition()

    /**
     * HA `user`: visible only to the listed user ids. The renderer can't read
     * the logged-in user's id today (it lives behind a `core/ha` change we
     * don't own), so the evaluator treats this as fail OPEN rather than hiding
     * a card the user most likely should see. Modelled (rather than collapsed
     * to [AlwaysTrue] at parse time) so a future change can supply the id and
     * flip the evaluator to a real membership test without touching the parser.
     */
    @Immutable
    data class User(val userIds: List<String>) : LovelaceCondition()

    /** Catch-all for a condition shape we can't evaluate. Fails CLOSED
     *  (hides the card) so an unmodelled condition never leaks a card HA
     *  would have hidden. */
    @Immutable
    data object Never : LovelaceCondition()

    /** A condition that is satisfied unconditionally. Reserved for shapes we
     *  deliberately treat as "always show" (e.g. an empty/degenerate rule);
     *  unmodelled shapes use [Never] instead. */
    @Immutable
    data object AlwaysTrue : LovelaceCondition()
}

/** Dashboard descriptor from `lovelace/dashboards/list`. The default
 *  dashboard is identified by a null [urlPath] (HA's convention). */
@Immutable
data class LovelaceDashboard(
    /** Stable id assigned by HA. Null for the default dashboard. */
    val id: String?,
    /**
     * URL path the user types in HA's web UI (`lovelace`, `energy`,
     * `my-dashboard`). Null means the default dashboard, which is what
     * the WS call expects when fetching its config too.
     */
    val urlPath: String?,
    val title: String,
    val icon: String?,
    val showInSidebar: Boolean,
    val requireAdmin: Boolean,
    /** `yaml` = config in storage / files; `storage` = UI-managed. */
    val mode: String?,
)
