package com.github.itskenny0.r1ha.core.lovelace

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Pure parser turning HA's raw `lovelace/config` JSON into the typed
 * [LovelaceConfig] tree. Stateless: no IO, no caching, no Compose.
 * Tested in isolation against fixture JSON.
 *
 * Design rules:
 *  - never throw on a card type / field we don't understand. Drop to
 *    [LovelaceCard.Unsupported] (whole card) or null (single field).
 *  - preserve the raw JSON inside every card so the editor + the debug
 *    expander on Unsupported cards can show the original payload.
 *  - mirror HA's tolerant shape: bare strings where objects are valid,
 *    missing keys with sensible defaults, mixed `service` / `action`
 *    field names for service calls.
 */
object LovelaceParser {

    /**
     * Matches a Home Assistant entity id (`domain.object_id`) embedded in a
     * larger string. Used to scrape an entity reference out of a Mushroom
     * template card's `primary` / `secondary` / `icon` template when the card
     * carries no explicit `entity` key.
     */
    private val ENTITY_ID_REGEX = Regex("""\b[a-z_]+\.[a-z0-9_]+\b""")

    /** Parse the top-level dashboard config returned by `lovelace/config`. */
    fun parseConfig(root: JsonObject): LovelaceConfig {
        val title = root["title"]?.asStringOrNull()
        val viewsArr = root["views"] as? JsonArray
        val views = viewsArr
            ?.mapIndexedNotNull { idx, el -> (el as? JsonObject)?.let { parseView(it, idx) } }
            ?: emptyList()
        // A fully strategy-generated dashboard (HA's auto default) returns
        // `{ "strategy": { ... } }` at the root with no concrete `views`. We
        // can't expand strategies locally, so flag it; the screen offers an
        // "open in Lovelace" affordance rather than rendering empty. Also flag
        // the degenerate case where the only views present are themselves all
        // strategy-driven (no concrete cards anywhere).
        val rootStrategy = root["strategy"] != null && (viewsArr == null || views.isEmpty())
        val allViewsStrategy = views.isNotEmpty() && views.all { it.isStrategyGenerated && it.cards.isEmpty() }
        return LovelaceConfig(
            title = title,
            views = views,
            isStrategyGenerated = rootStrategy || allViewsStrategy,
        )
    }

    /** Parse the dashboard list returned by `lovelace/dashboards/list`. */
    fun parseDashboards(arr: JsonArray): List<LovelaceDashboard> =
        arr.mapNotNull { el ->
            val obj = el as? JsonObject ?: return@mapNotNull null
            val urlPath = obj["url_path"]?.asStringOrNull()
            val title = obj["title"]?.asStringOrNull() ?: urlPath ?: return@mapNotNull null
            LovelaceDashboard(
                id = obj["id"]?.asStringOrNull(),
                urlPath = urlPath,
                title = title,
                icon = obj["icon"]?.asStringOrNull(),
                showInSidebar = obj["show_in_sidebar"]?.asBooleanOrNull() ?: true,
                requireAdmin = obj["require_admin"]?.asBooleanOrNull() ?: false,
                mode = obj["mode"]?.asStringOrNull(),
            )
        }

    private fun parseView(obj: JsonObject, index: Int): LovelaceView {
        val directCards = (obj["cards"] as? JsonArray)
            ?.mapNotNull { el -> (el as? JsonObject)?.let(::parseCard) }
            ?: emptyList()
        // "sections" views (HA's default UI-editor layout since 2024.x) hold
        // their cards under sections[].cards rather than the legacy top-level
        // cards[]. Without this a sections dashboard parses to zero cards and
        // renders as "0 entities". Flatten each concrete section's cards into
        // the view; a strategy section (cards generated by a server/client
        // strategy) carries no cards and is skipped, since we can't resolve
        // strategies locally.
        val sectionsArr = obj["sections"] as? JsonArray
        val sectionCards = sectionsArr
            ?.flatMap { sec -> (sec as? JsonObject)?.let(::parseSectionCards) ?: emptyList() }
            ?: emptyList()
        // A view is strategy-generated when it carries a `strategy:` key and no
        // concrete cards, OR every one of its sections is a strategy section
        // (carries `strategy` but no `cards`). Either way there is nothing for
        // us to render, so the screen can offer the Lovelace fallback per-view.
        val viewStrategy = obj["strategy"] != null
        val sectionsAllStrategy = sectionsArr != null && sectionsArr.isNotEmpty() &&
            sectionsArr.all { sec ->
                val s = sec as? JsonObject ?: return@all false
                s["strategy"] != null && (s["cards"] as? JsonArray).isNullOrEmpty()
            }
        val isStrategy = (directCards + sectionCards).isEmpty() && (viewStrategy || sectionsAllStrategy)
        return LovelaceView(
            title = obj["title"]?.asStringOrNull(),
            path = obj["path"]?.asStringOrNull() ?: index.toString(),
            icon = obj["icon"]?.asStringOrNull(),
            panel = obj["panel"]?.asBooleanOrNull() ?: false,
            cards = directCards + sectionCards,
            badges = parseBadges(obj["badges"]),
            isStrategyGenerated = isStrategy,
        )
    }

    /**
     * Parse a view's `badges:` array. HA accepts each entry as either a bare
     * entity-id string (`sensor.time`) or a `type: entity` object carrying
     * `show_name` / `show_state` / `show_icon` / `color` / `name` / `icon` /
     * `tap_action`. Both shapes resolve to a [LovelaceBadge]; a badge type we
     * don't model still yields a minimal chip (driven by its `entity` / `name`)
     * rather than being dropped, and an entry with neither is skipped.
     */
    private fun parseBadges(el: JsonElement?): List<LovelaceBadge> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { item ->
            when (item) {
                is JsonPrimitive -> if (item.isString && item.content.looksLikeEntityId()) {
                    LovelaceBadge(
                        entityId = item.content,
                        name = null,
                        icon = null,
                        color = null,
                        showName = false,
                        showState = true,
                        showIcon = true,
                        tapAction = null,
                    )
                } else {
                    null
                }
                is JsonObject -> {
                    val entity = item["entity"]?.asStringOrNull()?.takeIf { it.looksLikeEntityId() }
                    val name = item["name"]?.asStringOrNull()
                    val badgeType = item["type"]?.asStringOrNull()?.lowercase()
                    val tap = parseAction(item["tap_action"] as? JsonObject)
                    // A shortcut badge is action-driven and may carry only an
                    // icon; keep it as long as it has something to show or do.
                    val isShortcut = badgeType == "shortcut"
                    if (entity == null && name.isNullOrBlank() && !(isShortcut && (tap != null || item["icon"] != null))) {
                        return@mapNotNull null
                    }
                    LovelaceBadge(
                        entityId = entity,
                        name = name,
                        icon = item["icon"]?.asStringOrNull(),
                        color = item["color"]?.asStringOrNull(),
                        // HA's entity-badge defaults: state on, name off, icon on.
                        showName = item["show_name"]?.asBooleanOrNull() ?: false,
                        showState = item["show_state"]?.asBooleanOrNull() ?: true,
                        showIcon = item["show_icon"]?.asBooleanOrNull() ?: true,
                        tapAction = tap,
                    )
                }
                else -> null
            }
        }
    }

    /** Cards inside one section of a "sections" view. Strategy sections carry
     *  no concrete `cards` array and resolve to an empty list.
     *
     *  A section can carry its OWN `visibility:` conditions (HA gates the whole
     *  section on them). Because we flatten sections into the view's flat card
     *  list, that section-level gate would otherwise be lost and the section's
     *  cards would always show. Push the gate down onto every card in the
     *  section, wrapping each in a [LovelaceCard.Conditional]; this composes
     *  with any per-card `visibility:` (already applied by [parseCard]). */
    private fun parseSectionCards(section: JsonObject): List<LovelaceCard> {
        val cards = (section["cards"] as? JsonArray)
            ?.mapNotNull { el -> (el as? JsonObject)?.let(::parseCard) }
            ?: emptyList()
        val visibility = section["visibility"]
        if (visibility is JsonArray && visibility.isNotEmpty()) {
            val conditions = parseConditions(visibility)
            if (conditions.isNotEmpty()) {
                return cards.map { c ->
                    LovelaceCard.Conditional(raw = section, conditions = conditions, card = c)
                }
            }
        }
        return cards
    }

    /**
     * Recursive: stack and conditional cards re-enter the parser for
     * their children. Cycles aren't possible (HA's config is a tree).
     *
     * Honours the per-card `visibility:` key HA applies to ANY card type
     * (src/panels/lovelace/cards/hui-card.ts): a card with a non-empty
     * `visibility:` array is wrapped in a [LovelaceCard.Conditional] so it
     * renders only when every listed condition passes, exactly like an
     * explicit conditional card. This keeps a single evaluation + slicing
     * path for both forms.
     */
    fun parseCard(obj: JsonObject): LovelaceCard {
        val card = parseCardInner(obj)
        // Per-card `visibility:` wraps ANY card in conditional gating. HA
        // applies these in addition to (and outside of) a conditional card's
        // own conditions, so wrapping here composes correctly even when the
        // card is itself a `type: conditional`.
        val visibility = obj["visibility"]
        if (visibility is JsonArray && visibility.isNotEmpty()) {
            val conditions = parseConditions(visibility)
            if (conditions.isNotEmpty()) {
                return LovelaceCard.Conditional(
                    raw = obj,
                    conditions = conditions,
                    card = card,
                )
            }
        }
        return card
    }

    private fun parseCardInner(obj: JsonObject): LovelaceCard {
        val type = obj["type"]?.asStringOrNull()?.lowercase() ?: return LovelaceCard.Unsupported(obj, type = "(missing type)")
        return when (type) {
            "entities" -> LovelaceCard.Entities(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                showHeaderToggle = obj["show_header_toggle"]?.asBooleanOrNull(),
                entities = parseEntityRows(obj["entities"]),
            )
            "glance" -> LovelaceCard.Glance(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                columns = obj["columns"]?.asIntOrNull(),
                showName = obj["show_name"]?.asBooleanOrNull() ?: true,
                showState = obj["show_state"]?.asBooleanOrNull() ?: true,
                showIcon = obj["show_icon"]?.asBooleanOrNull() ?: true,
            )
            "button", "entity-button" -> LovelaceCard.Button(
                raw = obj,
                entityId = obj["entity"]?.asStringOrNull(),
                name = obj["name"]?.asStringOrNull(),
                icon = obj["icon"]?.asStringOrNull(),
                showName = obj["show_name"]?.asBooleanOrNull() ?: true,
                showIcon = obj["show_icon"]?.asBooleanOrNull() ?: true,
                showState = obj["show_state"]?.asBooleanOrNull() ?: false,
                tapAction = parseAction(obj["tap_action"] as? JsonObject),
            )
            "shortcut" -> LovelaceCard.Shortcut(
                raw = obj,
                name = obj["name"]?.asStringOrNull(),
                icon = obj["icon"]?.asStringOrNull(),
                color = obj["color"]?.asStringOrNull(),
                tapAction = parseAction(obj["tap_action"] as? JsonObject),
            )
            "tile" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Tile(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    icon = obj["icon"]?.asStringOrNull(),
                    hideState = obj["hide_state"]?.asBooleanOrNull() ?: false,
                    vertical = obj["vertical"]?.asBooleanOrNull() ?: false,
                    color = obj["color"]?.asStringOrNull(),
                    tapAction = parseAction(obj["tap_action"] as? JsonObject),
                    features = parseTileFeatures(obj["features"]),
                )
            }
            "light" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Light(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    icon = obj["icon"]?.asStringOrNull(),
                )
            }
            "gauge" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Gauge(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    unit = obj["unit"]?.asStringOrNull(),
                    min = obj["min"]?.asDoubleOrNull() ?: 0.0,
                    max = obj["max"]?.asDoubleOrNull() ?: 100.0,
                    needle = obj["needle"]?.asBooleanOrNull() ?: false,
                    severity = (obj["severity"] as? JsonObject)?.let { sev ->
                        GaugeSeverity(
                            green = sev["green"]?.asDoubleOrNull(),
                            yellow = sev["yellow"]?.asDoubleOrNull(),
                            red = sev["red"]?.asDoubleOrNull(),
                        )
                    },
                    segments = parseGaugeSegments(obj["segments"]),
                )
            }
            "weather-forecast" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.WeatherForecast(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    showCurrent = obj["show_current"]?.asBooleanOrNull() ?: true,
                    showForecast = obj["show_forecast"]?.asBooleanOrNull() ?: true,
                    forecastType = obj["forecast_type"]?.asStringOrNull(),
                    forecastSlots = obj["forecast_slots"]?.asIntOrNull(),
                )
            }
            "markdown" -> LovelaceCard.Markdown(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                content = obj["content"]?.asStringOrNull().orEmpty(),
            )
            "heading" -> LovelaceCard.Heading(
                raw = obj,
                heading = obj["heading"]?.asStringOrNull().orEmpty(),
                headingStyle = obj["heading_style"]?.asStringOrNull() ?: "title",
                icon = obj["icon"]?.asStringOrNull(),
            )
            "vertical-stack" -> LovelaceCard.VerticalStack(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                cards = parseChildCards(obj["cards"]),
            )
            "horizontal-stack" -> LovelaceCard.HorizontalStack(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                cards = parseChildCards(obj["cards"]),
            )
            "grid" -> LovelaceCard.Grid(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                columns = obj["columns"]?.asIntOrNull() ?: 3,
                square = obj["square"]?.asBooleanOrNull() ?: true,
                cards = parseChildCards(obj["cards"]),
            )
            "conditional" -> {
                val inner = obj["card"] as? JsonObject
                    ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Conditional(
                    raw = obj,
                    conditions = parseConditions(obj["conditions"]),
                    card = parseCard(inner),
                )
            }
            "sensor" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Sensor(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    icon = obj["icon"]?.asStringOrNull(),
                    unit = obj["unit"]?.asStringOrNull(),
                    // HA's only graph value that draws a line is "line"; "none"
                    // (the default) shows just the readout.
                    graph = obj["graph"]?.asStringOrNull()?.equals("line", ignoreCase = true) ?: false,
                    hoursToShow = obj["hours_to_show"]?.asIntOrNull() ?: 24,
                    detail = obj["detail"]?.asIntOrNull(),
                )
            }
            "picture-glance" -> LovelaceCard.PictureGlance(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                image = obj["image"]?.asStringOrNull(),
                cameraImage = obj["camera_image"]?.asStringOrNull() ?: obj["entity"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                tapAction = parseAction(obj["tap_action"] as? JsonObject),
            )
            "picture-entity" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.PictureEntity(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    image = obj["image"]?.asStringOrNull(),
                    showName = obj["show_name"]?.asBooleanOrNull() ?: true,
                    showState = obj["show_state"]?.asBooleanOrNull() ?: true,
                    tapAction = parseAction(obj["tap_action"] as? JsonObject),
                )
            }
            "area" -> {
                val area = obj["area"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Area(
                    raw = obj,
                    area = area,
                    name = obj["name"]?.asStringOrNull(),
                    image = obj["image"]?.asStringOrNull(),
                    entities = parseEntityRows(obj["entities"]),
                    navigationPath = obj["navigation_path"]?.asStringOrNull(),
                )
            }
            "history-graph" -> LovelaceCard.HistoryGraph(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                hoursToShow = obj["hours_to_show"]?.asIntOrNull() ?: 24,
            )
            "alarm-panel" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.AlarmPanel(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    states = (obj["states"] as? JsonArray)
                        ?.mapNotNull { it.asStringOrNull() }
                        ?: emptyList(),
                )
            }
            "map" -> LovelaceCard.Map(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                hoursToShow = obj["hours_to_show"]?.asIntOrNull(),
            )
            "thermostat" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Thermostat(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                )
            }
            "media-control" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.MediaControl(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                )
            }
            "humidifier" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Humidifier(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                )
            }
            "entity-filter" -> LovelaceCard.EntityFilter(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                stateFilter = parseStateFilter(obj["state_filter"]),
                showEmpty = obj["show_empty"]?.asBooleanOrNull() ?: true,
            )
            "statistic" -> {
                val entity = parseStatisticEntity(obj) ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Statistic(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    statType = obj["stat_type"]?.asStringOrNull()?.lowercase() ?: "mean",
                    period = parseStatisticPeriod(obj["period"]),
                )
            }
            "logbook" -> LovelaceCard.Logbook(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseLogbookEntities(obj),
                hoursToShow = obj["hours_to_show"]?.asIntOrNull() ?: 12,
            )
            "clock" -> LovelaceCard.Clock(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                showSeconds = obj["show_seconds"]?.asBooleanOrNull() ?: false,
                analog = obj["clock_style"]?.asStringOrNull()?.equals("analog", ignoreCase = true) ?: false,
            )
            "distribution" -> LovelaceCard.Distribution(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entries = parseDistributionEntries(obj["entities"]),
            )
            "iframe" -> bestEffortUnsupported(obj, type)
            else -> mapCustomCard(obj, type) ?: bestEffortUnsupported(obj, type)
        }
    }

    /**
     * Route a recognised community / custom card (`custom:*`) to the nearest
     * native [LovelaceCard] so it renders as a first-class tile instead of the
     * generic best-effort fallback with a raw "type:" caption.
     *
     * Returns null when the type isn't one we map, or when a mapping needs an
     * entity the config doesn't provide. The caller then falls through to
     * [bestEffortUnsupported], which keeps a tasteful placeholder.
     *
     * We deliberately reuse the existing native card variants rather than
     * inventing new ones: mushroom-* cards are thin styling wrappers around the
     * same entity controls HA's own cards expose, so a `mushroom-light-card`
     * maps cleanly onto our [LovelaceCard.Light], a `mushroom-climate-card`
     * onto [LovelaceCard.Thermostat], and so on. Cards without a dedicated
     * native twin (fan / cover / person / generic entity / template) map onto
     * [LovelaceCard.Tile], whose tap action already toggles or drills into the
     * entity per its domain. `mushroom-chips-card` maps onto [LovelaceCard.Glance]
     * (a compact row of entity chips), the closest native idiom.
     */
    private fun mapCustomCard(obj: JsonObject, type: String): LovelaceCard? {
        val normalized = type.removePrefix("custom:").lowercase()
        return when (normalized) {
            "mushroom-light-card" ->
                obj.entityIfPresent()?.let { entity ->
                    LovelaceCard.Light(
                        raw = obj,
                        entityId = entity,
                        name = obj["name"]?.asStringOrNull(),
                        icon = obj["icon"]?.asStringOrNull(),
                    )
                }
            "mushroom-media-player-card" ->
                obj.entityIfPresent()?.let { entity ->
                    LovelaceCard.MediaControl(
                        raw = obj,
                        entityId = entity,
                        name = obj["name"]?.asStringOrNull(),
                    )
                }
            "mushroom-climate-card" ->
                obj.entityIfPresent()?.let { entity ->
                    LovelaceCard.Thermostat(
                        raw = obj,
                        entityId = entity,
                        name = obj["name"]?.asStringOrNull(),
                    )
                }
            // Fan / cover / person / generic entity all map to the native Tile,
            // whose domain-aware default tap action does the right thing (toggle
            // a fan, open/close a cover, more-info a person) when no explicit
            // tap_action is configured.
            "mushroom-fan-card",
            "mushroom-cover-card",
            "mushroom-person-card",
            "mushroom-entity-card",
            ->
                obj.entityIfPresent()?.let { entity ->
                    tileFor(obj, entity, obj["name"]?.asStringOrNull(), obj["icon"]?.asStringOrNull())
                }
            "mushroom-template-card" -> mapTemplateCard(obj)
            "mushroom-chips-card" -> mapChipsCard(obj)
            "button-card" -> mapButtonCard(obj)
            else -> null
        }
    }

    /**
     * Mushroom template cards render arbitrary Jinja. We can't evaluate templates
     * client-side, so we map to a [LovelaceCard.Tile] best-effort: prefer the
     * explicit `entity`, else scrape the first entity id out of the `primary`,
     * `secondary`, or `icon` templates. `primary` becomes the tile name only when
     * it's plain text (no template markers); an `icon` is passed through only when
     * it's a literal `mdi:` glyph rather than a template.
     */
    private fun mapTemplateCard(obj: JsonObject): LovelaceCard? {
        val primary = obj["primary"]?.asStringOrNull()
        val secondary = obj["secondary"]?.asStringOrNull()
        val iconRaw = obj["icon"]?.asStringOrNull()
        val entity = obj.entityIfPresent()
            ?: extractEntityId(primary)
            ?: extractEntityId(secondary)
            ?: extractEntityId(iconRaw)
            ?: return null
        val name = primary?.takeIf { it.isPlainText() }
        val icon = iconRaw?.takeIf { it.isPlainText() }
        return tileFor(obj, entity, name, icon)
    }

    /** Build a Tile carrying the card's parsed tap_action (or null for the
     *  domain default applied at render time). */
    private fun tileFor(obj: JsonObject, entity: String, name: String?, icon: String?): LovelaceCard.Tile =
        LovelaceCard.Tile(
            raw = obj,
            entityId = entity,
            name = name,
            icon = icon,
            hideState = false,
            vertical = false,
            color = obj["icon_color"]?.asStringOrNull() ?: obj["color"]?.asStringOrNull(),
            tapAction = parseAction(obj["tap_action"] as? JsonObject),
        )

    /**
     * Map a mushroom chips card onto a native [LovelaceCard.Glance]: one chip per
     * entry that names an entity. Chips that carry no entity (weather / template /
     * conditional chips we can't resolve) are dropped. Returns null when nothing
     * usable remains, so the card falls back rather than rendering an empty glance.
     */
    private fun mapChipsCard(obj: JsonObject): LovelaceCard? {
        val chips = obj["chips"] as? JsonArray ?: return null
        val rows = chips.mapNotNull { chip ->
            val co = chip as? JsonObject ?: return@mapNotNull null
            val entity = co["entity"]?.asStringOrNull()?.takeIf { it.looksLikeEntityId() }
                ?: return@mapNotNull null
            EntityRow(
                entityId = entity,
                name = co["name"]?.asStringOrNull(),
                icon = co["icon"]?.asStringOrNull(),
                secondaryInfo = null,
            )
        }
        if (rows.isEmpty()) return null
        return LovelaceCard.Glance(
            raw = obj,
            title = obj["title"]?.asStringOrNull(),
            entities = rows,
            columns = null,
            showName = true,
            showState = true,
            showIcon = true,
        )
    }

    /**
     * Map a `custom:button-card` onto the native [LovelaceCard.Button]. button-card
     * configs almost always carry an `entity` and/or `name`; we surface both plus
     * the icon and preserve any `tap_action`, so it renders as a labelled,
     * actionable button rather than a bare "TAP" box. Requires at least an entity
     * or a name (a totally empty button-card has nothing to show).
     */
    private fun mapButtonCard(obj: JsonObject): LovelaceCard? {
        val entity = obj.entityIfPresent()
        val name = obj["name"]?.asStringOrNull()
        if (entity == null && name == null) return null
        return LovelaceCard.Button(
            raw = obj,
            entityId = entity,
            name = name,
            icon = obj["icon"]?.asStringOrNull(),
            showName = obj["show_name"]?.asBooleanOrNull() ?: true,
            showIcon = obj["show_icon"]?.asBooleanOrNull() ?: true,
            showState = obj["show_state"]?.asBooleanOrNull() ?: false,
            tapAction = parseAction(obj["tap_action"] as? JsonObject),
        )
    }

    /** The card's `entity` value, but only when it parses to a real entity id. */
    private fun JsonObject.entityIfPresent(): String? =
        this["entity"]?.asStringOrNull()?.takeIf { it.looksLikeEntityId() }

    /** First `domain.object_id` entity reference inside a (template) string, if any. */
    private fun extractEntityId(text: String?): String? {
        if (text == null) return null
        return ENTITY_ID_REGEX.find(text)?.value
    }

    /** True when a string is a literal value, not a Jinja template fragment. */
    private fun String.isPlainText(): Boolean = !contains("{{") && !contains("{%")

    /**
     * Build an [LovelaceCard.Unsupported] that captures whatever the renderer
     * can still make use of: entity refs (from `entity` / `entities`) and an
     * iframe `url`. Covers the long tail of `custom:*` cards so the renderer
     * can fall back to generic tiles / an embedded frame rather than a bare
     * placeholder. Cards with neither still resolve to a plain Unsupported and
     * keep the raw-JSON expander.
     */
    private fun bestEffortUnsupported(obj: JsonObject, type: String): LovelaceCard.Unsupported {
        val refs = LinkedHashSet<String>()
        obj["entity"]?.asStringOrNull()?.let { if (it.looksLikeEntityId()) refs.add(it) }
        (obj["entities"] as? JsonArray)?.forEach { item ->
            when (item) {
                is JsonPrimitive -> if (item.isString && item.content.looksLikeEntityId()) refs.add(item.content)
                is JsonObject -> item["entity"]?.asStringOrNull()?.let { if (it.looksLikeEntityId()) refs.add(it) }
                else -> Unit
            }
        }
        val url = obj["url"]?.asStringOrNull()?.takeUnless { it.isBlank() }
        // Strip a leading "custom:" so the caption reads "mushroom-light"
        // rather than "custom:mushroom-light".
        val friendly = type.removePrefix("custom:").ifBlank { type }
        return LovelaceCard.Unsupported(
            raw = obj,
            type = type,
            entityRefs = refs.toList(),
            url = url,
            friendlyType = friendly,
        )
    }

    /** Loose `domain.object_id` shape check so we don't pull non-entity
     *  strings (template snippets, css selectors) into the entity refs. */
    private fun String.looksLikeEntityId(): Boolean {
        val dot = indexOf('.')
        return dot > 0 && dot < length - 1 && none { it.isWhitespace() }
    }

    private fun parseChildCards(el: JsonElement?): List<LovelaceCard> =
        (el as? JsonArray)?.mapNotNull { (it as? JsonObject)?.let(::parseCard) }
            ?: emptyList()

    /**
     * Parse a tile card's `features:` array. Each entry is a `{type: ...}`
     * object (src/panels/lovelace/card-features/types.ts). We map the
     * high-value feature types onto the typed [LovelaceTileFeature] hierarchy
     * and keep an [LovelaceTileFeature.Unsupported] placeholder for the rest so
     * a future renderer can grow into them without a parser change. A bare
     * string or an entry without a `type` is dropped.
     */
    private fun parseTileFeatures(el: JsonElement?): List<LovelaceTileFeature> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { item ->
            val obj = item as? JsonObject ?: return@mapNotNull null
            val type = obj["type"]?.asStringOrNull()?.lowercase() ?: return@mapNotNull null
            when (type) {
                "cover-open-close" -> LovelaceTileFeature.CoverOpenClose
                "cover-position" -> LovelaceTileFeature.CoverPosition
                "light-brightness" -> LovelaceTileFeature.LightBrightness
                "fan-speed" -> LovelaceTileFeature.FanSpeed
                "climate-hvac-modes" -> LovelaceTileFeature.ClimateHvacModes(parseStringList(obj["hvac_modes"]))
                "alarm-modes" -> LovelaceTileFeature.AlarmModes(parseStringList(obj["modes"]))
                "lock-commands" -> LovelaceTileFeature.LockCommands
                "toggle" -> LovelaceTileFeature.Toggle
                "target-temperature" -> LovelaceTileFeature.TargetTemperature
                "select-options" -> LovelaceTileFeature.SelectOptions(parseStringList(obj["options"]))
                "media-player-playback" -> LovelaceTileFeature.MediaPlayback(parseStringList(obj["controls"]))
                "media-player-source" -> LovelaceTileFeature.MediaSource(parseStringList(obj["sources"]))
                "media-player-sound-mode" -> LovelaceTileFeature.MediaSoundMode(parseStringList(obj["sound_modes"]))
                "media-player-volume-buttons" -> LovelaceTileFeature.MediaVolumeButtons(
                    step = obj["step"]?.asIntOrNull() ?: 5,
                    showMute = obj["show_mute_button"]?.asBooleanOrNull() ?: false,
                )
                "media-player-volume-slider" -> LovelaceTileFeature.MediaVolumeSlider(
                    showMute = obj["show_mute_button"]?.asBooleanOrNull() ?: false,
                )
                else -> LovelaceTileFeature.Unsupported(type)
            }
        }
    }

    /**
     * Parse a gauge card's `segments:` array (HA's modern band format). Each
     * entry carries `from` (the lower bound the band starts at) and `color`
     * (a theme-colour name or `#rrggbb`). Entries missing either are dropped;
     * the list is sorted ascending by `from` so the renderer can fill each band
     * up to the next band's start, matching hui-gauge-card's `_severityLevels`.
     */
    private fun parseGaugeSegments(el: JsonElement?): List<GaugeSegment> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { item ->
            val obj = item as? JsonObject ?: return@mapNotNull null
            val from = obj["from"]?.asDoubleOrNull() ?: return@mapNotNull null
            val color = obj["color"]?.asStringOrNull()?.takeUnless { it.isBlank() } ?: return@mapNotNull null
            GaugeSegment(from = from, color = color)
        }.sortedBy { it.from }
    }

    /** Pull a list of plain strings out of a JSON array (filter feature configs
     *  like `hvac_modes:` / `modes:` / `options:`). Non-string entries dropped. */
    private fun parseStringList(el: JsonElement?): List<String> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { (it as? JsonPrimitive)?.let { p -> if (p.isString) p.content else null } }
    }

    private fun parseEntityRows(el: JsonElement?): List<EntityRow> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { item ->
            when (item) {
                is JsonPrimitive -> if (item.isString) {
                    EntityRow(
                        entityId = item.content,
                        name = null,
                        icon = null,
                        secondaryInfo = null,
                    )
                } else null
                is JsonObject -> {
                    val entity = item["entity"]?.asStringOrNull() ?: return@mapNotNull null
                    EntityRow(
                        entityId = entity,
                        name = item["name"]?.asStringOrNull(),
                        icon = item["icon"]?.asStringOrNull(),
                        secondaryInfo = item["secondary_info"]?.asStringOrNull(),
                    )
                }
                else -> null
            }
        }
    }

    /** Parse a distribution card's `entities:`: a bare id string or an object
     *  carrying `entity` / `name` / `color`. Entries without a usable id drop. */
    private fun parseDistributionEntries(el: JsonElement?): List<DistributionEntry> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { item ->
            when (item) {
                is JsonPrimitive -> if (item.isString) {
                    DistributionEntry(entityId = item.content, name = null, color = null)
                } else null
                is JsonObject -> {
                    val entity = item["entity"]?.asStringOrNull() ?: return@mapNotNull null
                    DistributionEntry(
                        entityId = entity,
                        name = item["name"]?.asStringOrNull(),
                        color = item["color"]?.asStringOrNull(),
                    )
                }
                else -> null
            }
        }
    }

    /**
     * Parse the `state_filter` of an entity-filter card. HA accepts either a
     * bare list of state strings (`["on", "home"]`) or a list of objects
     * carrying a `value` / `state` key (the richer operator form). We pull
     * the plain state value out of both shapes and ignore operators we can't
     * evaluate locally; the empty result means "no filter, show everything".
     */
    private fun parseStateFilter(el: JsonElement?): List<String> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { item ->
            when (item) {
                is JsonPrimitive -> if (item.isString) item.content else null
                is JsonObject -> item["value"]?.asStringOrNull() ?: item["state"]?.asStringOrNull()
                else -> null
            }
        }
    }

    /** Resolve the statistic card's entity id, accepting either the modern
     *  `entities: [id]` list or a bare `entity` string. */
    private fun parseStatisticEntity(obj: JsonObject): String? {
        (obj["entities"] as? JsonArray)?.firstOrNull()?.let { first ->
            when (first) {
                is JsonPrimitive -> if (first.isString) return first.content
                is JsonObject -> first["entity"]?.asStringOrNull()?.let { return it }
                else -> Unit
            }
        }
        return obj["entity"]?.asStringOrNull()
    }

    /** Normalise the statistic card's `period`. HA accepts a rich object
     *  (fixed_period / calendar / rolling_window) plus legacy string forms;
     *  we collapse to a coarse lookback bucket the renderer can act on. */
    private fun parseStatisticPeriod(el: JsonElement?): String {
        when (el) {
            is JsonPrimitive -> if (el.isString) return el.content.lowercase()
            is JsonObject -> {
                (el["calendar"] as? JsonObject)?.get("period")?.asStringOrNull()?.let { return it.lowercase() }
                if (el["fixed_period"] != null) return "month"
                if (el["rolling_window"] != null) return "week"
            }
            else -> Unit
        }
        return "day"
    }

    /** Logbook entity scope: prefer the modern `target.entity_id`, fall back
     *  to the deprecated `entities` list. Accepts a single id or an array. */
    private fun parseLogbookEntities(obj: JsonObject): List<String> {
        val out = LinkedHashSet<String>()
        val targetEntity = (obj["target"] as? JsonObject)?.get("entity_id")
        when (targetEntity) {
            is JsonPrimitive -> if (targetEntity.isString) out.add(targetEntity.content)
            is JsonArray -> targetEntity.forEach { it.asStringOrNull()?.let(out::add) }
            else -> Unit
        }
        when (val ents = obj["entities"]) {
            is JsonArray -> ents.forEach { item ->
                when (item) {
                    is JsonPrimitive -> if (item.isString) out.add(item.content)
                    is JsonObject -> item["entity"]?.asStringOrNull()?.let(out::add)
                    else -> Unit
                }
            }
            is JsonPrimitive -> if (ents.isString) out.add(ents.content)
            else -> Unit
        }
        return out.toList()
    }

    private fun parseAction(obj: JsonObject?): LovelaceAction? {
        if (obj == null) return null
        val actionName = obj["action"]?.asStringOrNull()?.lowercase() ?: return null
        return when (actionName) {
            "call-service", "perform-action" -> {
                // HA renamed `service` → `perform_action` in 2025.x; accept both.
                val service = obj["service"]?.asStringOrNull()
                    ?: obj["perform_action"]?.asStringOrNull()
                    ?: return null
                val target = obj["target"] as? JsonObject
                val entity = target?.get("entity_id")?.let { e ->
                    when (e) {
                        is JsonPrimitive -> e.contentOrNull()
                        is JsonArray -> e.firstOrNull()?.asStringOrNull()
                        else -> null
                    }
                } ?: obj["entity_id"]?.asStringOrNull()
                LovelaceAction.CallService(
                    service = service,
                    entityId = entity,
                    data = (obj["data"] as? JsonObject) ?: (obj["service_data"] as? JsonObject),
                )
            }
            "navigate" -> {
                val path = obj["navigation_path"]?.asStringOrNull() ?: return null
                LovelaceAction.Navigate(path = path)
            }
            "url" -> {
                val url = obj["url_path"]?.asStringOrNull() ?: obj["url"]?.asStringOrNull() ?: return null
                LovelaceAction.Url(url = url)
            }
            "toggle", "more-info", "none" -> LovelaceAction.Builtin(name = actionName)
            else -> LovelaceAction.Builtin(name = actionName)
        }
    }

    fun parseConditions(el: JsonElement?): List<LovelaceCondition> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { cond -> (cond as? JsonObject)?.let(::parseCondition) }
    }

    /**
     * Parse one condition object. Recursive for the `and` / `or` / `not`
     * groups. Mirrors HA's `checkConditionsMet` switch: a recognised shape we
     * can evaluate maps to its typed condition; a shape we can't (`time`,
     * `location`, `view_columns`, a `template`, or a malformed rule) maps to
     * [Never] so the card fails closed. `screen` fails open and `user` is
     * modelled (the evaluator fails it open today).
     */
    private fun parseCondition(obj: JsonObject): LovelaceCondition {
        val condition = obj["condition"]?.asStringOrNull()?.lowercase()
        val entity = obj["entity"]?.asStringOrNull()
        val attribute = obj["attribute"]?.asStringOrNull()
        return when {
            // `state` / `state_not` — HA's most common gate. Accepts a single
            // `state:` value or a `state:` list; `state_not` negates the match.
            // A state condition with no entity, or with neither state nor
            // state_not, can't be evaluated, so it fails closed.
            condition == "state" || condition == "state_not" ||
                (condition == null && entity != null) -> {
                if (entity == null) return LovelaceCondition.Never
                val negate = condition == "state_not" || obj["state_not"] != null
                val raw = if (negate) obj["state_not"] else obj["state"]
                val states = parseConditionStates(raw)
                if (states.isEmpty()) LovelaceCondition.Never
                else LovelaceCondition.StateEquals(
                    entityId = entity,
                    states = states,
                    negate = negate,
                    attribute = attribute,
                )
            }
            condition == "numeric_state" && entity != null -> {
                // A bound is either a literal number or a reference to another
                // entity's numeric state (HA's `above: sensor.x` form). We split
                // the two: a numeric string / number becomes a literal bound, an
                // entity-id-shaped string becomes an entity reference resolved at
                // evaluation time.
                val (above, aboveEntity) = parseNumericBound(obj["above"])
                val (below, belowEntity) = parseNumericBound(obj["below"])
                // A numeric_state with no usable bound at all can never be proven
                // (the reported `above: never` on a timestamp helper parsed to an
                // unbounded range that matched everything and leaked the card). With
                // nothing to compare on either side, fail closed.
                if (above == null && below == null && aboveEntity == null && belowEntity == null) {
                    LovelaceCondition.Never
                } else {
                    LovelaceCondition.NumericState(
                        entityId = entity,
                        above = above,
                        below = below,
                        aboveEntity = aboveEntity,
                        belowEntity = belowEntity,
                        attribute = attribute,
                    )
                }
            }
            // Logical groups recurse. An empty group is vacuously true for `and`
            // / `or` (matching HA), and a `not` over an empty group is true.
            // Unparseable children become [Never] (not dropped) so a group that
            // contains a condition we can't evaluate fails closed exactly the way
            // HA would, instead of silently passing on the evaluable siblings.
            condition == "and" -> LovelaceCondition.And(parseConditions(obj["conditions"]))
            condition == "or" -> LovelaceCondition.Or(parseConditions(obj["conditions"]))
            condition == "not" -> LovelaceCondition.Not(parseConditions(obj["conditions"]))
            // `user`: gated on the logged-in user id, which the renderer can't
            // read today. Modelled so a future change can evaluate it; for now
            // the evaluator fails it OPEN (see LovelaceCondition.User).
            condition == "user" -> LovelaceCondition.User(parseConditionStates(obj["users"]))
            // `screen` is a media-query breakpoint hint. We can't evaluate the
            // query locally, but on a single-window app the card is meant to be
            // visible, so fail OPEN rather than hiding content the user expects.
            condition == "screen" -> LovelaceCondition.AlwaysTrue
            // Conditions we can't evaluate locally — `time`, `location`,
            // `view_columns`, a `template`, or a malformed rule. HA evaluates
            // these server/client-side; we can't, so we fail closed and hide the
            // card rather than leaking it.
            else -> LovelaceCondition.Never
        }
    }

    /**
     * Split a numeric_state bound into (literalNumber, entityReference). HA
     * accepts a number, a numeric string, or an entity id (`sensor.x`) whose
     * live numeric state supplies the bound. Returns (null, null) for an
     * absent/unparseable bound, (n, null) for a literal, (null, id) for a
     * reference. A non-numeric, non-entity string (e.g. `never`) yields
     * (null, null) so the caller can fail closed.
     */
    private fun parseNumericBound(el: JsonElement?): Pair<Double?, String?> {
        if (el == null) return null to null
        el.asDoubleOrNull()?.let { return it to null }
        val s = el.asStringOrNull() ?: return null to null
        return if (s.looksLikeEntityId()) null to s else null to null
    }

    /**
     * Pull the accepted-state list out of a `state:` / `state_not:` value. HA
     * accepts either a single string or a list of strings; numbers/booleans are
     * coerced to their string form so `state: 1` and `state: on` both match.
     */
    private fun parseConditionStates(el: JsonElement?): List<String> = when (el) {
        null -> emptyList()
        is JsonArray -> el.mapNotNull { (it as? JsonPrimitive)?.contentOrNull() }
        is JsonPrimitive -> el.contentOrNull()?.let { listOf(it) } ?: emptyList()
        else -> emptyList()
    }

    // Per-element accessors that mirror HA's loose JSON shape: numbers
    // sometimes arrive as strings, booleans as 0/1, etc. Returning null
    // on shape-mismatch (rather than throwing) is intentional. every
    // call site has a sensible default to fall back to.

    private fun JsonElement.asStringOrNull(): String? =
        (this as? JsonPrimitive)?.contentOrNull()

    private fun JsonElement.asBooleanOrNull(): Boolean? {
        val prim = this as? JsonPrimitive ?: return null
        prim.booleanOrNull?.let { return it }
        return when (prim.content.lowercase()) {
            "true", "1", "yes", "on" -> true
            "false", "0", "no", "off" -> false
            else -> null
        }
    }

    private fun JsonElement.asIntOrNull(): Int? {
        val prim = this as? JsonPrimitive ?: return null
        return prim.intOrNull ?: prim.content.toIntOrNull()
    }

    private fun JsonElement.asDoubleOrNull(): Double? {
        val prim = this as? JsonPrimitive ?: return null
        return prim.doubleOrNull ?: prim.content.toDoubleOrNull()
    }

    private fun JsonPrimitive.contentOrNull(): String? =
        if (this is JsonNull) null else content
}
