package com.github.itskenny0.r1ha.core.lovelace

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Pure parser turning HA's raw `lovelace/config` JSON into the typed
 * [LovelaceConfig] tree. Stateless: no IO, no caching, no Compose.
 * Tested in isolation against fixture JSON.
 *
 * Design rules:
 *  - never throw on a card type / field we don't understand. Drop to
 *    [LovelaceCard.Unsupported] (whole card) or null (single field).
 *  - preserve the raw JSON inside every card so the editor + the debug
 *    expander on Unsupported cards can show the original payload.
 *  - mirror HA's tolerant shape: bare strings where objects are valid,
 *    missing keys with sensible defaults, mixed `service` / `action`
 *    field names for service calls.
 */
object LovelaceParser {

    /** Parse the top-level dashboard config returned by `lovelace/config`. */
    fun parseConfig(root: JsonObject): LovelaceConfig {
        val title = root["title"]?.asStringOrNull()
        val viewsArr = root["views"] as? JsonArray
        val views = viewsArr
            ?.mapIndexedNotNull { idx, el -> (el as? JsonObject)?.let { parseView(it, idx) } }
            ?: emptyList()
        // A fully strategy-generated dashboard (HA's auto default) returns
        // `{ "strategy": { ... } }` at the root with no concrete `views`. We
        // can't expand strategies locally, so flag it; the screen offers an
        // "open in Lovelace" affordance rather than rendering empty. Also flag
        // the degenerate case where the only views present are themselves all
        // strategy-driven (no concrete cards anywhere).
        val rootStrategy = root["strategy"] != null && (viewsArr == null || views.isEmpty())
        val allViewsStrategy = views.isNotEmpty() && views.all { it.isStrategyGenerated && it.cards.isEmpty() }
        return LovelaceConfig(
            title = title,
            views = views,
            isStrategyGenerated = rootStrategy || allViewsStrategy,
        )
    }

    /** Parse the dashboard list returned by `lovelace/dashboards/list`. */
    fun parseDashboards(arr: JsonArray): List<LovelaceDashboard> =
        arr.mapNotNull { el ->
            val obj = el as? JsonObject ?: return@mapNotNull null
            val urlPath = obj["url_path"]?.asStringOrNull()
            val title = obj["title"]?.asStringOrNull() ?: urlPath ?: return@mapNotNull null
            LovelaceDashboard(
                id = obj["id"]?.asStringOrNull(),
                urlPath = urlPath,
                title = title,
                icon = obj["icon"]?.asStringOrNull(),
                showInSidebar = obj["show_in_sidebar"]?.asBooleanOrNull() ?: true,
                requireAdmin = obj["require_admin"]?.asBooleanOrNull() ?: false,
                mode = obj["mode"]?.asStringOrNull(),
            )
        }

    private fun parseView(obj: JsonObject, index: Int): LovelaceView {
        val directCards = (obj["cards"] as? JsonArray)
            ?.mapNotNull { el -> (el as? JsonObject)?.let(::parseCard) }
            ?: emptyList()
        // "sections" views (HA's default UI-editor layout since 2024.x) hold
        // their cards under sections[].cards rather than the legacy top-level
        // cards[]. Without this a sections dashboard parses to zero cards and
        // renders as "0 entities". Flatten each concrete section's cards into
        // the view; a strategy section (cards generated by a server/client
        // strategy) carries no cards and is skipped, since we can't resolve
        // strategies locally.
        val sectionsArr = obj["sections"] as? JsonArray
        val sectionCards = sectionsArr
            ?.flatMap { sec -> (sec as? JsonObject)?.let(::parseSectionCards) ?: emptyList() }
            ?: emptyList()
        // A view is strategy-generated when it carries a `strategy:` key and no
        // concrete cards, OR every one of its sections is a strategy section
        // (carries `strategy` but no `cards`). Either way there is nothing for
        // us to render, so the screen can offer the Lovelace fallback per-view.
        val viewStrategy = obj["strategy"] != null
        val sectionsAllStrategy = sectionsArr != null && sectionsArr.isNotEmpty() &&
            sectionsArr.all { sec ->
                val s = sec as? JsonObject ?: return@all false
                s["strategy"] != null && (s["cards"] as? JsonArray).isNullOrEmpty()
            }
        val isStrategy = (directCards + sectionCards).isEmpty() && (viewStrategy || sectionsAllStrategy)
        return LovelaceView(
            title = obj["title"]?.asStringOrNull(),
            path = obj["path"]?.asStringOrNull() ?: index.toString(),
            icon = obj["icon"]?.asStringOrNull(),
            panel = obj["panel"]?.asBooleanOrNull() ?: false,
            cards = directCards + sectionCards,
            isStrategyGenerated = isStrategy,
        )
    }

    /** Cards inside one section of a "sections" view. Strategy sections carry
     *  no concrete `cards` array and resolve to an empty list. */
    private fun parseSectionCards(section: JsonObject): List<LovelaceCard> =
        (section["cards"] as? JsonArray)
            ?.mapNotNull { el -> (el as? JsonObject)?.let(::parseCard) }
            ?: emptyList()

    /**
     * Recursive: stack and conditional cards re-enter the parser for
     * their children. Cycles aren't possible (HA's config is a tree).
     */
    fun parseCard(obj: JsonObject): LovelaceCard {
        val type = obj["type"]?.asStringOrNull()?.lowercase() ?: return LovelaceCard.Unsupported(obj, type = "(missing type)")
        return when (type) {
            "entities" -> LovelaceCard.Entities(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                showHeaderToggle = obj["show_header_toggle"]?.asBooleanOrNull(),
                entities = parseEntityRows(obj["entities"]),
            )
            "glance" -> LovelaceCard.Glance(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                columns = obj["columns"]?.asIntOrNull(),
                showName = obj["show_name"]?.asBooleanOrNull() ?: true,
                showState = obj["show_state"]?.asBooleanOrNull() ?: true,
                showIcon = obj["show_icon"]?.asBooleanOrNull() ?: true,
            )
            "button", "entity-button" -> LovelaceCard.Button(
                raw = obj,
                entityId = obj["entity"]?.asStringOrNull(),
                name = obj["name"]?.asStringOrNull(),
                icon = obj["icon"]?.asStringOrNull(),
                showName = obj["show_name"]?.asBooleanOrNull() ?: true,
                showIcon = obj["show_icon"]?.asBooleanOrNull() ?: true,
                showState = obj["show_state"]?.asBooleanOrNull() ?: false,
                tapAction = parseAction(obj["tap_action"] as? JsonObject),
            )
            "tile" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Tile(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    icon = obj["icon"]?.asStringOrNull(),
                    hideState = obj["hide_state"]?.asBooleanOrNull() ?: false,
                    vertical = obj["vertical"]?.asBooleanOrNull() ?: false,
                    color = obj["color"]?.asStringOrNull(),
                    tapAction = parseAction(obj["tap_action"] as? JsonObject),
                )
            }
            "light" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Light(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    icon = obj["icon"]?.asStringOrNull(),
                )
            }
            "gauge" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Gauge(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    unit = obj["unit"]?.asStringOrNull(),
                    min = obj["min"]?.asDoubleOrNull() ?: 0.0,
                    max = obj["max"]?.asDoubleOrNull() ?: 100.0,
                    needle = obj["needle"]?.asBooleanOrNull() ?: false,
                    severity = (obj["severity"] as? JsonObject)?.let { sev ->
                        GaugeSeverity(
                            green = sev["green"]?.asDoubleOrNull(),
                            yellow = sev["yellow"]?.asDoubleOrNull(),
                            red = sev["red"]?.asDoubleOrNull(),
                        )
                    },
                )
            }
            "weather-forecast" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.WeatherForecast(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    showCurrent = obj["show_current"]?.asBooleanOrNull() ?: true,
                    showForecast = obj["show_forecast"]?.asBooleanOrNull() ?: true,
                    forecastType = obj["forecast_type"]?.asStringOrNull(),
                    forecastSlots = obj["forecast_slots"]?.asIntOrNull(),
                )
            }
            "markdown" -> LovelaceCard.Markdown(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                content = obj["content"]?.asStringOrNull().orEmpty(),
            )
            "heading" -> LovelaceCard.Heading(
                raw = obj,
                heading = obj["heading"]?.asStringOrNull().orEmpty(),
                headingStyle = obj["heading_style"]?.asStringOrNull() ?: "title",
                icon = obj["icon"]?.asStringOrNull(),
            )
            "vertical-stack" -> LovelaceCard.VerticalStack(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                cards = parseChildCards(obj["cards"]),
            )
            "horizontal-stack" -> LovelaceCard.HorizontalStack(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                cards = parseChildCards(obj["cards"]),
            )
            "grid" -> LovelaceCard.Grid(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                columns = obj["columns"]?.asIntOrNull() ?: 3,
                square = obj["square"]?.asBooleanOrNull() ?: true,
                cards = parseChildCards(obj["cards"]),
            )
            "conditional" -> {
                val inner = obj["card"] as? JsonObject
                    ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Conditional(
                    raw = obj,
                    conditions = parseConditions(obj["conditions"]),
                    card = parseCard(inner),
                )
            }
            "sensor" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Sensor(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    icon = obj["icon"]?.asStringOrNull(),
                    unit = obj["unit"]?.asStringOrNull(),
                    // HA's only graph value that draws a line is "line"; "none"
                    // (the default) shows just the readout.
                    graph = obj["graph"]?.asStringOrNull()?.equals("line", ignoreCase = true) ?: false,
                    hoursToShow = obj["hours_to_show"]?.asIntOrNull() ?: 24,
                    detail = obj["detail"]?.asIntOrNull(),
                )
            }
            "picture-glance" -> LovelaceCard.PictureGlance(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                image = obj["image"]?.asStringOrNull(),
                cameraImage = obj["camera_image"]?.asStringOrNull() ?: obj["entity"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                tapAction = parseAction(obj["tap_action"] as? JsonObject),
            )
            "picture-entity" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.PictureEntity(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    image = obj["image"]?.asStringOrNull(),
                    showName = obj["show_name"]?.asBooleanOrNull() ?: true,
                    showState = obj["show_state"]?.asBooleanOrNull() ?: true,
                    tapAction = parseAction(obj["tap_action"] as? JsonObject),
                )
            }
            "area" -> {
                val area = obj["area"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Area(
                    raw = obj,
                    area = area,
                    name = obj["name"]?.asStringOrNull(),
                    image = obj["image"]?.asStringOrNull(),
                    entities = parseEntityRows(obj["entities"]),
                    navigationPath = obj["navigation_path"]?.asStringOrNull(),
                )
            }
            "history-graph" -> LovelaceCard.HistoryGraph(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                hoursToShow = obj["hours_to_show"]?.asIntOrNull() ?: 24,
            )
            "alarm-panel" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.AlarmPanel(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    states = (obj["states"] as? JsonArray)
                        ?.mapNotNull { it.asStringOrNull() }
                        ?: emptyList(),
                )
            }
            "map" -> LovelaceCard.Map(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                hoursToShow = obj["hours_to_show"]?.asIntOrNull(),
            )
            "thermostat" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Thermostat(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                )
            }
            "media-control" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.MediaControl(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                )
            }
            "humidifier" -> {
                val entity = obj["entity"]?.asStringOrNull() ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Humidifier(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                )
            }
            "entity-filter" -> LovelaceCard.EntityFilter(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseEntityRows(obj["entities"]),
                stateFilter = parseStateFilter(obj["state_filter"]),
                showEmpty = obj["show_empty"]?.asBooleanOrNull() ?: true,
            )
            "statistic" -> {
                val entity = parseStatisticEntity(obj) ?: return LovelaceCard.Unsupported(obj, type)
                LovelaceCard.Statistic(
                    raw = obj,
                    entityId = entity,
                    name = obj["name"]?.asStringOrNull(),
                    statType = obj["stat_type"]?.asStringOrNull()?.lowercase() ?: "mean",
                    period = parseStatisticPeriod(obj["period"]),
                )
            }
            "logbook" -> LovelaceCard.Logbook(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                entities = parseLogbookEntities(obj),
                hoursToShow = obj["hours_to_show"]?.asIntOrNull() ?: 12,
            )
            "clock" -> LovelaceCard.Clock(
                raw = obj,
                title = obj["title"]?.asStringOrNull(),
                showSeconds = obj["show_seconds"]?.asBooleanOrNull() ?: false,
                analog = obj["clock_style"]?.asStringOrNull()?.equals("analog", ignoreCase = true) ?: false,
            )
            "iframe" -> bestEffortUnsupported(obj, type)
            else -> bestEffortUnsupported(obj, type)
        }
    }

    /**
     * Build an [LovelaceCard.Unsupported] that captures whatever the renderer
     * can still make use of: entity refs (from `entity` / `entities`) and an
     * iframe `url`. Covers the long tail of `custom:*` cards so the renderer
     * can fall back to generic tiles / an embedded frame rather than a bare
     * placeholder. Cards with neither still resolve to a plain Unsupported and
     * keep the raw-JSON expander.
     */
    private fun bestEffortUnsupported(obj: JsonObject, type: String): LovelaceCard.Unsupported {
        val refs = LinkedHashSet<String>()
        obj["entity"]?.asStringOrNull()?.let { if (it.looksLikeEntityId()) refs.add(it) }
        (obj["entities"] as? JsonArray)?.forEach { item ->
            when (item) {
                is JsonPrimitive -> if (item.isString && item.content.looksLikeEntityId()) refs.add(item.content)
                is JsonObject -> item["entity"]?.asStringOrNull()?.let { if (it.looksLikeEntityId()) refs.add(it) }
                else -> Unit
            }
        }
        val url = obj["url"]?.asStringOrNull()?.takeUnless { it.isBlank() }
        // Strip a leading "custom:" so the caption reads "mushroom-light"
        // rather than "custom:mushroom-light".
        val friendly = type.removePrefix("custom:").ifBlank { type }
        return LovelaceCard.Unsupported(
            raw = obj,
            type = type,
            entityRefs = refs.toList(),
            url = url,
            friendlyType = friendly,
        )
    }

    /** Loose `domain.object_id` shape check so we don't pull non-entity
     *  strings (template snippets, css selectors) into the entity refs. */
    private fun String.looksLikeEntityId(): Boolean {
        val dot = indexOf('.')
        return dot > 0 && dot < length - 1 && none { it.isWhitespace() }
    }

    private fun parseChildCards(el: JsonElement?): List<LovelaceCard> =
        (el as? JsonArray)?.mapNotNull { (it as? JsonObject)?.let(::parseCard) }
            ?: emptyList()

    private fun parseEntityRows(el: JsonElement?): List<EntityRow> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { item ->
            when (item) {
                is JsonPrimitive -> if (item.isString) {
                    EntityRow(
                        entityId = item.content,
                        name = null,
                        icon = null,
                        secondaryInfo = null,
                    )
                } else null
                is JsonObject -> {
                    val entity = item["entity"]?.asStringOrNull() ?: return@mapNotNull null
                    EntityRow(
                        entityId = entity,
                        name = item["name"]?.asStringOrNull(),
                        icon = item["icon"]?.asStringOrNull(),
                        secondaryInfo = item["secondary_info"]?.asStringOrNull(),
                    )
                }
                else -> null
            }
        }
    }

    /**
     * Parse the `state_filter` of an entity-filter card. HA accepts either a
     * bare list of state strings (`["on", "home"]`) or a list of objects
     * carrying a `value` / `state` key (the richer operator form). We pull
     * the plain state value out of both shapes and ignore operators we can't
     * evaluate locally; the empty result means "no filter, show everything".
     */
    private fun parseStateFilter(el: JsonElement?): List<String> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { item ->
            when (item) {
                is JsonPrimitive -> if (item.isString) item.content else null
                is JsonObject -> item["value"]?.asStringOrNull() ?: item["state"]?.asStringOrNull()
                else -> null
            }
        }
    }

    /** Resolve the statistic card's entity id, accepting either the modern
     *  `entities: [id]` list or a bare `entity` string. */
    private fun parseStatisticEntity(obj: JsonObject): String? {
        (obj["entities"] as? JsonArray)?.firstOrNull()?.let { first ->
            when (first) {
                is JsonPrimitive -> if (first.isString) return first.content
                is JsonObject -> first["entity"]?.asStringOrNull()?.let { return it }
                else -> Unit
            }
        }
        return obj["entity"]?.asStringOrNull()
    }

    /** Normalise the statistic card's `period`. HA accepts a rich object
     *  (fixed_period / calendar / rolling_window) plus legacy string forms;
     *  we collapse to a coarse lookback bucket the renderer can act on. */
    private fun parseStatisticPeriod(el: JsonElement?): String {
        when (el) {
            is JsonPrimitive -> if (el.isString) return el.content.lowercase()
            is JsonObject -> {
                (el["calendar"] as? JsonObject)?.get("period")?.asStringOrNull()?.let { return it.lowercase() }
                if (el["fixed_period"] != null) return "month"
                if (el["rolling_window"] != null) return "week"
            }
            else -> Unit
        }
        return "day"
    }

    /** Logbook entity scope: prefer the modern `target.entity_id`, fall back
     *  to the deprecated `entities` list. Accepts a single id or an array. */
    private fun parseLogbookEntities(obj: JsonObject): List<String> {
        val out = LinkedHashSet<String>()
        val targetEntity = (obj["target"] as? JsonObject)?.get("entity_id")
        when (targetEntity) {
            is JsonPrimitive -> if (targetEntity.isString) out.add(targetEntity.content)
            is JsonArray -> targetEntity.forEach { it.asStringOrNull()?.let(out::add) }
            else -> Unit
        }
        when (val ents = obj["entities"]) {
            is JsonArray -> ents.forEach { item ->
                when (item) {
                    is JsonPrimitive -> if (item.isString) out.add(item.content)
                    is JsonObject -> item["entity"]?.asStringOrNull()?.let(out::add)
                    else -> Unit
                }
            }
            is JsonPrimitive -> if (ents.isString) out.add(ents.content)
            else -> Unit
        }
        return out.toList()
    }

    private fun parseAction(obj: JsonObject?): LovelaceAction? {
        if (obj == null) return null
        val actionName = obj["action"]?.asStringOrNull()?.lowercase() ?: return null
        return when (actionName) {
            "call-service", "perform-action" -> {
                // HA renamed `service` → `perform_action` in 2025.x; accept both.
                val service = obj["service"]?.asStringOrNull()
                    ?: obj["perform_action"]?.asStringOrNull()
                    ?: return null
                val target = obj["target"] as? JsonObject
                val entity = target?.get("entity_id")?.let { e ->
                    when (e) {
                        is JsonPrimitive -> e.contentOrNull()
                        is JsonArray -> e.firstOrNull()?.asStringOrNull()
                        else -> null
                    }
                } ?: obj["entity_id"]?.asStringOrNull()
                LovelaceAction.CallService(
                    service = service,
                    entityId = entity,
                    data = (obj["data"] as? JsonObject) ?: (obj["service_data"] as? JsonObject),
                )
            }
            "navigate" -> {
                val path = obj["navigation_path"]?.asStringOrNull() ?: return null
                LovelaceAction.Navigate(path = path)
            }
            "url" -> {
                val url = obj["url_path"]?.asStringOrNull() ?: obj["url"]?.asStringOrNull() ?: return null
                LovelaceAction.Url(url = url)
            }
            "toggle", "more-info", "none" -> LovelaceAction.Builtin(name = actionName)
            else -> LovelaceAction.Builtin(name = actionName)
        }
    }

    private fun parseConditions(el: JsonElement?): List<LovelaceCondition> {
        val arr = el as? JsonArray ?: return emptyList()
        return arr.mapNotNull { cond ->
            val obj = cond as? JsonObject ?: return@mapNotNull null
            val condition = obj["condition"]?.asStringOrNull()?.lowercase()
            val entity = obj["entity"]?.asStringOrNull()
            when {
                // `state` / `state_not` — HA's most common gate. Accepts a single
                // `state:` value or a `state:` list; `state_not` negates the match.
                // A state condition with no entity, or with neither state nor
                // state_not, can't be evaluated, so it fails closed.
                condition == "state" || condition == "state_not" ||
                    (condition == null && entity != null) -> {
                    if (entity == null) return@mapNotNull LovelaceCondition.Never
                    val negate = condition == "state_not" || obj["state_not"] != null
                    val raw = if (negate) obj["state_not"] else obj["state"]
                    val states = parseConditionStates(raw)
                    if (states.isEmpty()) LovelaceCondition.Never
                    else LovelaceCondition.StateEquals(entityId = entity, states = states, negate = negate)
                }
                condition == "numeric_state" && entity != null -> LovelaceCondition.NumericState(
                    entityId = entity,
                    above = obj["above"]?.asDoubleOrNull(),
                    below = obj["below"]?.asDoubleOrNull(),
                )
                // Conditions we can't evaluate locally — `screen` (media-query
                // breakpoints), `user` (logged-in user id), template conditions,
                // an `and`/`or`/`not` group, or a malformed rule. HA evaluates
                // these server/client-side; we can't, so we fail closed and hide
                // the card rather than leaking it.
                else -> LovelaceCondition.Never
            }
        }
    }

    /**
     * Pull the accepted-state list out of a `state:` / `state_not:` value. HA
     * accepts either a single string or a list of strings; numbers/booleans are
     * coerced to their string form so `state: 1` and `state: on` both match.
     */
    private fun parseConditionStates(el: JsonElement?): List<String> = when (el) {
        null -> emptyList()
        is JsonArray -> el.mapNotNull { (it as? JsonPrimitive)?.contentOrNull() }
        is JsonPrimitive -> el.contentOrNull()?.let { listOf(it) } ?: emptyList()
        else -> emptyList()
    }

    // Per-element accessors that mirror HA's loose JSON shape: numbers
    // sometimes arrive as strings, booleans as 0/1, etc. Returning null
    // on shape-mismatch (rather than throwing) is intentional. every
    // call site has a sensible default to fall back to.

    private fun JsonElement.asStringOrNull(): String? =
        (this as? JsonPrimitive)?.contentOrNull()

    private fun JsonElement.asBooleanOrNull(): Boolean? {
        val prim = this as? JsonPrimitive ?: return null
        prim.booleanOrNull?.let { return it }
        return when (prim.content.lowercase()) {
            "true", "1", "yes", "on" -> true
            "false", "0", "no", "off" -> false
            else -> null
        }
    }

    private fun JsonElement.asIntOrNull(): Int? {
        val prim = this as? JsonPrimitive ?: return null
        return prim.intOrNull ?: prim.content.toIntOrNull()
    }

    private fun JsonElement.asDoubleOrNull(): Double? {
        val prim = this as? JsonPrimitive ?: return null
        return prim.doubleOrNull ?: prim.content.toDoubleOrNull()
    }

    private fun JsonPrimitive.contentOrNull(): String? =
        if (this is JsonNull) null else content
}
