package com.github.itskenny0.r1ha.core.lovelace

import androidx.compose.runtime.Immutable
import kotlinx.serialization.json.JsonObject

/**
 * Typed in-memory model for a parsed HA Lovelace dashboard configuration.
 *
 * Mirrors the subset of `lovelace/config` shape that the dashboards renderer
 * understands today. Any card type we don't model is preserved as
 * [LovelaceCard.Unsupported] with its raw JSON payload intact, so the screen
 * can still show a placeholder + the original config for debugging without
 * dropping it from the view.
 *
 * Read-only on R1HA's side: parsing happens once per dashboard fetch and the
 * tree is treated as immutable. Local-only edits land as a separate overrides
 * layer (see [LovelaceOverrides]) keyed by `(viewPath, cardIndex)`, applied at
 * render time so the imported HA config is never mutated.
 *
 * @Immutable so Compose can skip recomposition when references haven't changed.
 */
@Immutable
data class LovelaceConfig(
    val title: String?,
    val views: List<LovelaceView>,
    /**
     * `true` when the dashboard is entirely generated by an HA *strategy*
     * (the `strategy:` key at the config root, with no concrete `views`).
     * HA's default auto-dashboard is the canonical example: the server only
     * returns `{ "strategy": { "type": "original-states" } }` and expects the
     * frontend to expand it client-side, which R1HA can't do natively. The
     * screen reads this flag to show an "open in Lovelace" affordance instead
     * of silently rendering an empty dashboard.
     */
    val isStrategyGenerated: Boolean = false,
)

/** One view inside a dashboard. corresponds to a tab in HA's frontend. */
@Immutable
data class LovelaceView(
    /** User-facing title; falls back to the path or index when empty. */
    val title: String?,
    /**
     * URL-style identifier HA uses to address the view (e.g. "lights",
     * "default_view"). Stable across HA restarts; we key local overrides
     * against it so reordering views in HA doesn't shuffle our overrides.
     * Falls back to the index-as-string when the YAML omits it.
     */
    val path: String,
    /** Optional MDI icon string (`mdi:lightbulb` etc.). */
    val icon: String?,
    /**
     * `true` when the view should render its cards in panel mode (single
     * card filling the viewport). We honour this when rendering: a `panel: true`
     * view with one card hides the surrounding scroll/padding chrome.
     */
    val panel: Boolean,
    /**
     * The parsed cards in display order. Empty when the view exists but
     * has no cards (legitimate during early-edit on HA's side).
     */
    val cards: List<LovelaceCard>,
    /**
     * `true` when this view delegates its layout to an HA *strategy* (a
     * `strategy:` key on the view, or on every one of its sections) and so
     * carries no concrete cards we can render. The screen surfaces the
     * "open in Lovelace" affordance for such a view rather than an empty
     * scroll. A view that mixes a strategy section with concrete sections
     * keeps the concrete cards and is NOT flagged.
     */
    val isStrategyGenerated: Boolean = false,
)

/**
 * Sealed hierarchy of card types R1HA renders natively. Adding a new
 * type means: declare a data class here, parse it in [LovelaceParser],
 * and add a branch in [com.github.itskenny0.r1ha.feature.dashboards.cards.LovelaceCardRenderer].
 *
 * Every variant carries [raw] so the editor's JSON view can show + edit
 * the original config without round-tripping through our typed model
 * (which would silently drop fields we don't understand yet).
 */
@Immutable
sealed class LovelaceCard {
    /** Card type string from the original config (`"entities"`, `"tile"`, etc.). */
    abstract val type: String

    /** Raw JSON config as HA returned it; the editor + Unsupported renderer
     *  both rely on this being preserved verbatim. */
    abstract val raw: JsonObject

    /** Vertical list of entity rows. */
    @Immutable
    data class Entities(
        override val raw: JsonObject,
        val title: String?,
        val showHeaderToggle: Boolean?,
        val entities: List<EntityRow>,
    ) : LovelaceCard() {
        override val type: String = "entities"
    }

    /** Compact grid of entity glyphs + state readouts. */
    @Immutable
    data class Glance(
        override val raw: JsonObject,
        val title: String?,
        val entities: List<EntityRow>,
        val columns: Int?,
        val showName: Boolean,
        val showState: Boolean,
        val showIcon: Boolean,
    ) : LovelaceCard() {
        override val type: String = "glance"
    }

    /** Single tappable action button. Either a bare action (no entity) or
     *  wired to a specific entity for state-coloured display. */
    @Immutable
    data class Button(
        override val raw: JsonObject,
        val entityId: String?,
        val name: String?,
        val icon: String?,
        val showName: Boolean,
        val showIcon: Boolean,
        val showState: Boolean,
        val tapAction: LovelaceAction?,
    ) : LovelaceCard() {
        override val type: String = "button"
    }

    /** Modern compact tile (HA's current first-class card type). */
    @Immutable
    data class Tile(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val icon: String?,
        val hideState: Boolean,
        val vertical: Boolean,
        val color: String?,
        val tapAction: LovelaceAction?,
    ) : LovelaceCard() {
        override val type: String = "tile"
    }

    /** Dedicated light card. Brightness + on/off; for full colour control
     *  the card-stack archetype is still the right surface. */
    @Immutable
    data class Light(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val icon: String?,
    ) : LovelaceCard() {
        override val type: String = "light"
    }

    /** Gauge readout for one numeric entity. */
    @Immutable
    data class Gauge(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val unit: String?,
        val min: Double,
        val max: Double,
        val needle: Boolean,
        val severity: GaugeSeverity?,
    ) : LovelaceCard() {
        override val type: String = "gauge"
    }

    /** Weather card with current conditions + optional forecast strip. */
    @Immutable
    data class WeatherForecast(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val showCurrent: Boolean,
        val showForecast: Boolean,
        val forecastType: String?,
        val forecastSlots: Int?,
    ) : LovelaceCard() {
        override val type: String = "weather-forecast"
    }

    /** Markdown body, optionally Jinja-templated at render time. */
    @Immutable
    data class Markdown(
        override val raw: JsonObject,
        val title: String?,
        val content: String,
    ) : LovelaceCard() {
        override val type: String = "markdown"
    }

    /** Static section heading inside a view. */
    @Immutable
    data class Heading(
        override val raw: JsonObject,
        val heading: String,
        val headingStyle: String,
        val icon: String?,
    ) : LovelaceCard() {
        override val type: String = "heading"
    }

    /** Vertical stack of child cards. */
    @Immutable
    data class VerticalStack(
        override val raw: JsonObject,
        val title: String?,
        val cards: List<LovelaceCard>,
    ) : LovelaceCard() {
        override val type: String = "vertical-stack"
    }

    /** Horizontal stack of child cards. */
    @Immutable
    data class HorizontalStack(
        override val raw: JsonObject,
        val title: String?,
        val cards: List<LovelaceCard>,
    ) : LovelaceCard() {
        override val type: String = "horizontal-stack"
    }

    /** Grid of child cards in `columns` columns. */
    @Immutable
    data class Grid(
        override val raw: JsonObject,
        val title: String?,
        val columns: Int,
        val square: Boolean,
        val cards: List<LovelaceCard>,
    ) : LovelaceCard() {
        override val type: String = "grid"
    }

    /** Shows its [card] only when every condition in [conditions] passes. */
    @Immutable
    data class Conditional(
        override val raw: JsonObject,
        val conditions: List<LovelaceCondition>,
        val card: LovelaceCard,
    ) : LovelaceCard() {
        override val type: String = "conditional"
    }

    /**
     * Single-entity sensor card. Shows the friendly name + current value
     * and, when `graph: line`, a small history line chart of the sensor's
     * recent values (fetched lazily by the renderer).
     */
    @Immutable
    data class Sensor(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val icon: String?,
        val unit: String?,
        /** `true` when HA's `graph: line` is set; renders the history chart. */
        val graph: Boolean,
        /** Hours of history the line graph spans (HA's `hours_to_show`). */
        val hoursToShow: Int,
        val detail: Int?,
    ) : LovelaceCard() {
        override val type: String = "sensor"
    }

    /**
     * Picture card with overlaid entity chips. Background is a static
     * [image] URL or, when [cameraImage] / an `entity` with an
     * `entity_picture` is set, that entity's picture. [entities] render as
     * small state chips along the bottom edge.
     */
    @Immutable
    data class PictureGlance(
        override val raw: JsonObject,
        val title: String?,
        /** Static background image URL (`image:`). Null when driven by an entity picture. */
        val image: String?,
        /** Entity whose `entity_picture` attribute supplies the background. */
        val cameraImage: String?,
        val entities: List<EntityRow>,
        val tapAction: LovelaceAction?,
    ) : LovelaceCard() {
        override val type: String = "picture-glance"
    }

    /**
     * Picture card bound to a single entity. Background image (static or the
     * entity's `entity_picture`) with the entity's name + state overlaid;
     * tapping fires the entity's action.
     */
    @Immutable
    data class PictureEntity(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        val image: String?,
        val showName: Boolean,
        val showState: Boolean,
        val tapAction: LovelaceAction?,
    ) : LovelaceCard() {
        override val type: String = "picture-entity"
    }

    /**
     * Area card: an area name + a representative strip of the area's
     * controls / sensors. R1HA can't resolve an area's member entities
     * locally (that needs the area registry), so the card renders the
     * configured [name]/[area] heading plus any explicitly-listed
     * [entities]; an area with no listed entities shows just the heading.
     */
    @Immutable
    data class Area(
        override val raw: JsonObject,
        /** HA `area` id. */
        val area: String,
        val name: String?,
        val image: String?,
        /** Entities the config explicitly attached to the area card, if any. */
        val entities: List<EntityRow>,
        val navigationPath: String?,
    ) : LovelaceCard() {
        override val type: String = "area"
    }

    /**
     * History-graph card: a multi-entity history line chart. The renderer
     * fetches each entity's history and overlays the numeric series on a
     * shared canvas; non-numeric entities are skipped from the line plot.
     */
    @Immutable
    data class HistoryGraph(
        override val raw: JsonObject,
        val title: String?,
        val entities: List<EntityRow>,
        val hoursToShow: Int,
    ) : LovelaceCard() {
        override val type: String = "history-graph"
    }

    /** Alarm-panel keypad card. Mirrors the cardstack AlarmPanel. */
    @Immutable
    data class AlarmPanel(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
        /** Subset of HA's `states` config (arm modes to surface). Empty = all. */
        val states: List<String>,
    ) : LovelaceCard() {
        override val type: String = "alarm-panel"
    }

    /**
     * Map card: entities with `latitude`/`longitude` attributes plotted on
     * an abstract canvas (mirrors the Zones map). No real map tiles.
     */
    @Immutable
    data class Map(
        override val raw: JsonObject,
        val title: String?,
        val entities: List<EntityRow>,
        val hoursToShow: Int?,
    ) : LovelaceCard() {
        override val type: String = "map"
    }

    /**
     * Thermostat card bound to one `climate.*` entity. Surfaces the current
     * temperature reading, a target-setpoint stepper, and the HVAC-mode chip
     * row (gated on the entity's advertised `hvac_modes`). Mirrors the
     * card-stack climate control idiom; service calls ride the standard
     * [LovelaceAction.CallService] path.
     */
    @Immutable
    data class Thermostat(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
    ) : LovelaceCard() {
        override val type: String = "thermostat"
    }

    /**
     * Media-control card bound to one `media_player.*` entity. Shows the
     * now-playing line, a transport row (previous / play-pause / next), and a
     * volume stepper, each gated on the player's advertised
     * `supported_features`. Service calls ride the standard
     * [LovelaceAction.CallService] path.
     */
    @Immutable
    data class MediaControl(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
    ) : LovelaceCard() {
        override val type: String = "media-control"
    }

    /**
     * Humidifier card bound to one `humidifier.*` entity. Surfaces an on/off
     * toggle, the target-humidity stepper, and the available-mode chip row
     * (when the entity advertises `available_modes`). Service calls ride the
     * standard [LovelaceAction.CallService] path.
     */
    @Immutable
    data class Humidifier(
        override val raw: JsonObject,
        val entityId: String,
        val name: String?,
    ) : LovelaceCard() {
        override val type: String = "humidifier"
    }

    /** Any card type we don't natively render.
     *
     * Best-effort fallback: even for a type we don't model, most cards carry
     * enough JSON to render *something* more useful than a raw dump. The
     * parser captures:
     *  - [entityRefs]: entity ids pulled from an `entity` (string) or
     *    `entities` (array) key. Covers the bulk of `custom:*` cards
     *    (mushroom-*, button-card, etc.); the renderer shows a generic tile
     *    per ref with live state + tap-to-toggle.
     *  - [url]: the `url` of an `iframe` card, which the renderer embeds in a
     *    sandboxed WebView.
     *  - [friendlyType]: a human-readable label for the caption (the raw
     *    `custom:` prefix stripped), falling back to [type].
     *
     * When none of these are present the renderer keeps the original
     * placeholder + expandable raw-JSON affordance. */
    @Immutable
    data class Unsupported(
        override val raw: JsonObject,
        override val type: String,
        val entityRefs: List<String> = emptyList(),
        val url: String? = null,
        val friendlyType: String = type,
    ) : LovelaceCard()
}

/**
 * One row inside an entities-card-like list (entities / glance).
 *
 * HA accepts either a bare entity_id string or a richer object with name +
 * icon + secondary_info overrides; both shapes resolve to this same row.
 */
@Immutable
data class EntityRow(
    val entityId: String,
    /** Override label; null falls back to the entity's `friendly_name`. */
    val name: String?,
    /** Override icon string ("mdi:lightbulb"). Null = derived from domain. */
    val icon: String?,
    /**
     * What to render in the small secondary line under the primary state.
     * HA accepts a fixed enum: "last-changed", "last-triggered",
     * "last-updated", "area", "position", "state", "tilt-position",
     * "brightness", "entity-id". Free-form for now; renderers handle the
     * subset that maps cleanly to data we already have.
     */
    val secondaryInfo: String?,
)

/**
 * Subset of HA's action_config we understand. Tap on a button card or
 * tile card fires one of these; unknown variants degrade to a no-op.
 */
@Immutable
sealed class LovelaceAction {
    @Immutable
    data class CallService(
        val service: String,
        val entityId: String?,
        val data: JsonObject?,
    ) : LovelaceAction()

    @Immutable
    data class Navigate(val path: String) : LovelaceAction()

    @Immutable
    data class Url(val url: String) : LovelaceAction()

    /** `toggle` / `more-info` / `none`. */
    @Immutable
    data class Builtin(val name: String) : LovelaceAction()
}

/** Severity bands for the gauge card. colour the needle when the value
 *  passes a threshold. */
@Immutable
data class GaugeSeverity(
    val green: Double?,
    val yellow: Double?,
    val red: Double?,
)

/**
 * Condition for [LovelaceCard.Conditional]. We model the two most common
 * shapes (state equals / numeric state) and treat anything else as a
 * permissive `true` so the wrapped card always renders rather than being
 * silently hidden by an unsupported condition.
 */
@Immutable
sealed class LovelaceCondition {
    @Immutable
    data class StateEquals(val entityId: String, val state: String) : LovelaceCondition()

    @Immutable
    data class NumericState(
        val entityId: String,
        val above: Double?,
        val below: Double?,
    ) : LovelaceCondition()

    /** Catch-all: condition shape we don't understand. Evaluates to true. */
    @Immutable
    data object AlwaysTrue : LovelaceCondition()
}

/** Dashboard descriptor from `lovelace/dashboards/list`. The default
 *  dashboard is identified by a null [urlPath] (HA's convention). */
@Immutable
data class LovelaceDashboard(
    /** Stable id assigned by HA. Null for the default dashboard. */
    val id: String?,
    /**
     * URL path the user types in HA's web UI (`lovelace`, `energy`,
     * `my-dashboard`). Null means the default dashboard, which is what
     * the WS call expects when fetching its config too.
     */
    val urlPath: String?,
    val title: String,
    val icon: String?,
    val showInSidebar: Boolean,
    val requireAdmin: Boolean,
    /** `yaml` = config in storage / files; `storage` = UI-managed. */
    val mode: String?,
)
